### ISSUE TITLE
Images overlap columns

### ISSUE THREAD

**Issue by richmccartney** [ubuntudesign/vanilla-framework#144]
So currently if you were to place an image with a greater width inside of a column it will overlap like so, this doesn't look great and we should incorporate what we had from ubuntu guidelines into vanilla.
 
![screen shot 2015-04-15 at 17 09 48](https://cloud.githubusercontent.com/assets/1201618/7162021/9564e9ec-e392-11e4-9f62-88cbf7a68179.png)

**Comment by yaili** [comment]
@anthonydillon Isn't this the issue you're fixing?

**Comment by anthonydillon** [comment]
Yes will be fixed today..  Promise

**Comment by anthonydillon** [comment]
Fixed now.
