### ISSUE TITLE
Improve CSS in header.scss

### ISSUE THREAD

**Issue by richmccartney** [ubuntudesign/vanilla-framework#148]
Looking through the header.scss file feel like it needs a little love, especially in the medium break point area. A bit of a prune and a clear up would totally benefit it. When looking at the cloud styles with vanilla there were a few annoyances we could clear up.

**Comment by richmccartney** [comment]
Adding this to the v0.0.13 milestone, could be achieved in the refactoring in our week sprint.

**Comment by barrymcgee** [comment]
@richmccartney Was this work completed? If so, can you close this issue please :)

**Comment by yaili** [comment]
@richmccartney see above, pls

**Comment by yaili** [comment]
@anthonydillon @richmccartney Was this completed?

**Comment by anthonydillon** [comment]
No still need refactoring. Hopefully a Friday project for someone.
