### ISSUE TITLE
Disabled form elements do not look disabled

### ISSUE THREAD

**Issue by richmccartney** [ubuntudesign/vanilla-framework#154]
Looking at a disabled input element it still looks exactly the same as a normal active input. Can we amend the styling not to confuse people who see this.

![screen shot 2015-04-28 at 10 40 03](https://cloud.githubusercontent.com/assets/1201618/7367213/bbb2bd38-ed95-11e4-802f-f76e4cbbc599.png)

**Comment by anthonydillon** [comment]
This looks different for me. Which browser are you setting this?

**Comment by richmccartney** [comment]
@anthonydillon this is in Safari
