### ISSUE TITLE
Remove Ubuntu colours from Vanilla

### ISSUE THREAD

**Issue by richmccartney** [ubuntudesign/vanilla-framework#156]
Looking at the vanilla theme its still very *ubuntu* we should look at the styles Jamie & Spencer created and start to pull out the orange and make it far more of a blank slate.

**Comment by richmccartney** [comment]
@anthonydillon do you have any thoughts on what else we might need to change to make things a bit more **vanilla** over old **ubuntu** styles.

**Comment by anthonydillon** [comment]
We should set the brand cloud to light grey and create a var to change the
main nav link color.

**Comment by richmccartney** [comment]
@anthonydillon I believe this is now closed thanks to your header update.
