### ISSUE TITLE
Dropdown button styling

### ISSUE THREAD

**Issue by jamiedawsonyoung** [ubuntudesign/vanilla-framework#171]
Can we make the padding etc the same as on Maas (@richmccartney) and use the chevron? 

Understand that when you click the drop-down the styling will be dictated by the browser / OS

**Comment by yaili** [comment]
@richmccartney Can you provide a screenshot of what @jamiedawsonyoung refers to?

**Comment by anthonydillon** [comment]
I strongly disagree with changing to default browser dropdown as this
involves rebuilding the browser functionality in divs and js. The browsers
have full assessibilty support which we would have to support if we rebuild
it.

That said we can modify the style of the input (not the dropdown) in
WebKit. This can be seen here as the sort by and series filters;
https://jujucharms.com/store

**Comment by yaili** [comment]
Is that not the default WebKit style?

**Comment by anthonydillon** [comment]
We have increased the padding, changed the background to white instead of
the gradient and added a dark grey border.

**Comment by yaili** [comment]
The only thing that changes on Chrome is the font size that I can see…

I'm guessing @Lucapaulina et al. might come up with suggestions for styles of select elements… I'd like to explore this further.

Some examples to think about:

- http://ux.mailchimp.com/patterns/forms#select-dijit
- http://getbootstrap.com/css/#selects

**Comment by anthonydillon** [comment]
Sorry here is the styled dropdowns:
https://demo.jujucharms.com/services/?store

**Comment by yaili** [comment]
Could that not be the default for vanilla? It follows the styles of the other inputs.

**Comment by Lucapaulina** [comment]
I can't see why it couldn't be used.

**Comment by anthonydillon** [comment]
Sure we could add it. I'll gather the styles and add them to this issue to
be worked on.

**Comment by richmccartney** [comment]
Here are the current MAAS GUI styles for select dropdown as per Jamie's original comments

<img width="801" alt="screen shot 2016-02-19 at 22 42 55" src="https://cloud.githubusercontent.com/assets/1201618/13191229/3383e7d4-d75a-11e5-850b-f474a8883f7a.png">
<img width="742" alt="screen shot 2016-02-19 at 22 42 48" src="https://cloud.githubusercontent.com/assets/1201618/13191230/33b4e938-d75a-11e5-9656-59e2875f2777.png">

**Comment by yaili** [comment]
@anthonydillon @jamiedawsonyoung @richmccartney We decided we'd keep default radio and checkboxes for Vanilla. Shouldn't select inputs follow the same rationale in that case?

**Comment by anthonydillon** [comment]
Oh did we, I thought we were using the positive colour for them. It is a
design decision really.

**Comment by yaili** [comment]
Positive colour only for Juju (green) and MAAS (orange).

**Comment by jamiedawsonyoung** [comment]
Isn't it a little odd to have a different colour for selection controls for each product? I'm not sure they should be 'branded' I think we could come up with a consistent style for all? (green like Client?) ;-)

**Comment by yaili** [comment]
Yes, that's what we talked about at the workshop, if I understood correctly. The idea is that we'd leave them as they are for now, but the products should align at some point (soon).

**Comment by yaili** [comment]
Added wontfix label. Correct me if I understood wrong, but I think the current agreement is that Vanilla will have unstyled checkboxes, radio buttons and select inputs (dropdowns).
