### ISSUE TITLE
Can we add the colour palette to the framework? 

### ISSUE THREAD

**Issue by jamiedawsonyoung** [ubuntudesign/vanilla-framework#174]
This is in the Google doc: https://docs.google.com/a/canonical.com/document/d/1f2XGx2qBL6QBDsY0w9v15c_JJwauyx3jwRWmCRHaKnM/edit?usp=sharing

But also here: 

* Brand colour: #dd4814 (depends on the brand)
* Text grey: #333333
* Dark grey: #888888
* Mid grey: #CDCDCD
* Light grey: #F7F7F7
* White: #ffffff
* Status success (green): #38b44a
* Status warning (yellow): #eca918
* Status error (red): #df382c
* Status information (blue): #19b6ee

**Comment by anthonydillon** [comment]
I think the correct home for this would be the web style guide on design.ubuntu.com. do you agree?

**Comment by richmccartney** [comment]
@anthonydillon I think it would still be helpful to see the full pallet on the demo just so we know what is being changed.

**Comment by anthonydillon** [comment]
The idea of the demo is to show live components of the framework. The place to find available variables would be the docs.

**Comment by jamiedawsonyoung** [comment]
Okay, I think what @anthonydillon says makes sense. It was just to get an overview of the palette. If you think it's better to feature this on design.ubuntu.com then we can do that.
