### ISSUE TITLE
unordered and ordered list styling

### ISSUE THREAD

**Issue by jamiedawsonyoung** [ubuntudesign/vanilla-framework#176]
Can we make the colour of the numeral or the bullet point: #888888

**Comment by yaili** [comment]
I would prefer if we leave this as simple as possible. I think the solution for this is using :before, correct? @anthonydillon

**Comment by anthonydillon** [comment]
Yea that's correct.

**Comment by yaili** [comment]
I'm going to mark this as won't fix.
