### ISSUE TITLE
Table styling

### ISSUE THREAD

**Issue by jamiedawsonyoung** [ubuntudesign/vanilla-framework#179]
There are some rules for table styling in the Google doc: 

* Table header
 * h4. 1.250 / 1.3
* Row titles
 * p. 1.000 / 1.5
 * Colour #888888
* Title hr
 * 1px solid hr
 * Colour #cdcdcd
* row hr
 * 1px dotted hr
 * Colour #cdcdcd
* row hover
 * Colour #F7F7F7

**Comment by anthonydillon** [comment]
This is great! Sorry I missed it from the original doc. The only think missing is cell spacing/padding. We can discuss tomorrow if that is OK.

**Comment by jamiedawsonyoung** [comment]
I'll assign this to me for now so I know that I need to define this

**Comment by yaili** [comment]
Is this done? Can we close it?

**Comment by anthonydillon** [comment]
Not sure, will check. I think we should revisit the table component and
give it's a overhaul.

**Comment by yaili** [comment]
I agree. I'll assign it to me.

**Comment by yaili** [comment]
I'm sure we agreed on tables for Vanilla at the offsite, but I can't find my notes. Will update when I do.

**Comment by yaili** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;WOGiIjat&#x2F;1493-define-table-styling"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Define table styling</a>

**Comment by yaili** [comment]
Table style should follow existing Juju table style, which is similar to MAAS but more neutral.

Notes:
- dotted lines should be used to divide rows that are part of the same section, otherwise solid lines should be used
- headers should be same font size as cell text, in regular (400) font weight
- no vertical dividers
