### ISSUE TITLE
The length of vertical dividers

### ISSUE THREAD

**Issue by jamiedawsonyoung** [ubuntudesign/vanilla-framework#180]
Is is possible to have the length of the vertical dividers match the tallest column in the row? 

For instance, if a column of text has less text in it than the others, the vertical divider that is associated with it is shorter (and looks odd). 

Are we able to apply the same rules we use in "Equal Heights" to the vertical dividers?

**Comment by anthonydillon** [comment]
This can be achieved by combining vertical dividers and equal heights. Not sure we need to show combinations of components in the demo page. We can chat about it tomorrow.

**Comment by richmccartney** [comment]
I'll create and test to see if these both work correctly on the demo just so we have a good example. Or maybe add another class to make sure this happens on just the vertical dividers.

**Comment by anthonydillon** [comment]
This is a dup of https://github.com/ubuntudesign/vanilla-framework/issues/237
