### ISSUE TITLE
Remove navigation bevel

### ISSUE THREAD

**Issue by richmccartney** [ubuntudesign/vanilla-framework#184]
Remove the bevel colour styles for the header navigation and look more to a Cloud style for inspiration.

**Comment by yaili** [comment]
Has this been done?

**Comment by anthonydillon** [comment]
Do we want this as default? This would involve removing the bevel style
from Vanilla and add it to Ubuntu theme.

**Comment by yaili** [comment]
When I look at the navigation header in the demo I see no bevel. Am I looking at the wrong thing?

**Comment by anthonydillon** [comment]
The bevel is referring to the dark line on the right of a main navigation
and the light border on the left of the links. Which gives the links a
bevelled look.

**Comment by yaili** [comment]
Oh I see. Yes I suppose it shouldn't have it.
