### ISSUE TITLE
Box design

### ISSUE THREAD

**Issue by richmccartney** [ubuntudesign/vanilla-framework#186]
A box styles to vanilla.

**Comment by anthonydillon** [comment]
@yaili what should the default box style be?

**Comment by yaili** [comment]
grey border, white background?

**Comment by anthonydillon** [comment]
That's what I was thinking. Something super simple for Vanilla. This sound
right?

```css
border: 1px solid $warm-grey;
padding: 20px;
background-colour: $white;
```

**Comment by yaili** [comment]
Yes. And rounded corners?

**Comment by anthonydillon** [comment]
Oh yea, not sure. I think You and Spencer should talk about the default
style.

**Comment by yaili** [comment]
I think that vanilla should include both simple and highlighted box styles. I think for now we might have to say:

- default vanilla is what is currently on ubuntu.com in terms of rounded corners
- current square juju style is a variation

Not sure what the default vanilla drop shadow is, but if Juju is more consistent that ubuntu.com we could decide that juju style is the default one for vanilla.

Make sense?

**Comment by yaili** [comment]
Thinking about this again, the header style is square in vanilla, so perhaps it makes more sense to have square cornered boxes in vanilla with added rounded corners to ubuntu, in that case Juju would be following plain vanilla style.

**Comment by anthonydillon** [comment]
Totally, thank you.

**Comment by anthonydillon** [comment]
Sounds good.

**Comment by yaili** [comment]
Agreed styles:

- **.box** (part of Vanilla)
 - background: transparent
 - border: warm-grey
 - no rounded corners (this is added by theme)
- **.card** (part of Vanilla)
 - background: white
 - border: @faooful @spencerbygraves can you clarify, I had "grey" in my notes, but that doesn't sound right
- **.box-overlay** (part of Vanilla)
 - background: white
 - background opacity: 0.85
 - padding: 20px
- **.card-resource** (part of Ubuntu theme)
 - example: http://www.ubuntu.com/cloud/openstack/managed-cloud (end of page)

Utility class:

- **.layer**: defines drop shadow
 - mentioned using 200…900 but this was not agreed. Perhaps easier to use 1, 2, 3, …

**Comment by faooful** [comment]
@yaili  #CDCDCD is the colour that we use for the border with a 2px radius.

**Comment by yaili** [comment]
@faooful in the .card too? what is the spec for the shadow?

**Comment by faooful** [comment]
@yaili  oh for the card, sorry, we just have drop shadow + the 2px radius.

**Comment by barrymcgee** [comment]
The dev team is meeting next week to discuss Vanilla naming & structure which will heavily inform how this issue will be actioned. 

It would also seem to be that "boxes" and "cards" are two distinct patterns and shouldn't be conflated? More info is needed here so de-prioritising for now.
