### ISSUE TITLE
Button and link button size inconsistency

### ISSUE THREAD

**Issue by jamiedawsonyoung** [ubuntudesign/vanilla-framework#191]
Looking on Firefox the button and link button look different. Looks like a padding issue

**Comment by yaili** [comment]
Still valid.

**Comment by barrymcgee** [comment]
I spoke with @carlaberkers and others over email and suggested the best way to address multiple threads of discussion over buttons would be a small workshop to collate and rationalise. Therefore, I'm going to move this issue back into the backlog (ditto #228) but assign it to the `v1.0` milestone to ensure it's addressed before that release.

**Comment by yaili** [comment]
@barrymcgee Why is it "more info needed"? It's confirmed.
