### ISSUE TITLE
Equal heights issue on Safari

### ISSUE THREAD

**Issue by richmccartney** [ubuntudesign/vanilla-framework#193]
Looking at the equal heights block I get this issue of it not working. I have uploaded a screenshot as reference. Safari version 8.0.6.

![equal-heights](https://cloud.githubusercontent.com/assets/1201618/8155837/0a016a1e-1340-11e5-943e-05470602edf0.jpg)

**Comment by anthonydillon** [comment]
I believe this is due to a missing webkit prefix: http://caniuse.com/#feat=flexbox

**Comment by yaili** [comment]
@anthonydillon Has this been fixed?

**Comment by anthonydillon** [comment]
@richmccartney I can't replicate this. Using Safari 8 I get this:
![dashboard](https://cloud.githubusercontent.com/assets/1413534/13246514/01a7034a-da0c-11e5-800a-93e25706ca1b.png)

Could you test again and let us know if you still see that same issue?
