### ISSUE TITLE
Links are white (and therefore invisible)

### ISSUE THREAD

**Issue by svijee** [ubuntudesign/vanilla-framework#204]
All text links are white. And you can't read "white on white" pretty well. ;)

You can verify that on the [Demopage](https://ubuntudesign.github.io/vanilla-framework/demo/#). E.g. the links to "Legal information" and "Report a bug on this site" in the footer.

**Comment by anthonydillon** [comment]
Thank you Sujeevan, you are absolutely correct. They should be styled with the link color variable which is set to orange by default.

**Comment by anthonydillon** [comment]
This has landed.
