### ISSUE TITLE
Update @import configuration to work with NPM v3

### ISSUE THREAD

**Issue by nottrobin** [ubuntudesign/vanilla-framework#211]
[NPM version 3](https://github.com/npm/npm/releases/tag/v3.0.0) is coming soon and includes a breaking change for vanilla in that the structure of installed modules will change. Thanks @anthonydillon for pointing this out.

We now need to accommodate all the modules being installed in the same `node_modules` folder at the root of the project.

**Comment by nottrobin** [comment]
How about we leverage [SASS_PATH](http://technology.customink.com/blog/2014/10/09/understanding-and-using-sass-load-paths/), so that instead of each attempt to import `vanilla` having to know where to locate it, the client will have the responsibility of making sure the relevant modules are available in the `SASS_PATH`.

This would mean, in all themes ([ubuntu](https://github.com/ubuntudesign/ubuntu-vanilla-theme/), [canonical](https://github.com/ubuntudesign/canonical-vanilla-theme/), [cloud](https://github.com/ubuntudesign/cloud-vanilla-theme/)) and in all sites that include them, we change the relative `@import` lines, so e.g.:

    @import '../node_modules/vanilla-framework/scss/vanilla';

would become

    @import 'vanilla-framework/scss/vanilla';

Which would work as long as you run `sass` similar to as follows:

    SASS_PATH=node_modules sass --update static/css

**Comment by anthonydillon** [comment]
Thanks @nottrobin for formalising this issue. I like the idea but takes an extra piece of configuration. All themes and and framework will now reside together so wouldn't that make the relative linking easier?

**Comment by nottrobin** [comment]
The extra configuration can easily be swept out of site into a make target.

I really think this is neater than relative linking because it can accommodate both, and it means you (and forkers from the community) can in theory keep your modules wherever you like. The framework just asks for the module, it doesn't need to know where to find it.

I can easily write make (or npm) targets to check which version of npm you're using and set the SASS_PATH accordingly. This way you guys don't need to do extra work and you're still free to experiment with npm 3 locally if you want.

**Comment by nottrobin** [comment]
It also means if you want to develop, say, ubuntu-website bit using you local checkouts of ubuntu-vanilla-theme and vanilla-framework, could could simply put the locations of those checkouts in your SASS_PATH rather the mess of creating the whole node_modules hierarchy every time.

E.g.:

SASS_PATH=~/projects sass ...

**Comment by anthonydillon** [comment]
Sounds good too me. It's basically relative pathing until the SASS_PATH is
modified. Let's make a card for the work required to add the version check
and SASS_PATH.

**Comment by nottrobin** [comment]
It will also mean we no longer get issues with `../` not playing nicely with certain sass compilers.

**Comment by barrymcgee** [comment]
Related: #264

**Comment by barrymcgee** [comment]
This has now been resolved by #368
