### ISSUE TITLE
Headings

### ISSUE THREAD

**Issue by richmccartney** [ubuntudesign/vanilla-framework#224]
While sat in a coffee shop working on some Sass I've come up with this idea for all headings, thoughts on this code and if we like we should implement it.

@anthonydillon @deadlight @grahambancroft 

```
  // Headings
  $h1:                    36px!default;
  $h2:                    30px!default;
  $h3:                    24px!default;
  $h4:                    20px!default;
  $h5:                    16px!default;
  $h6:                    14px!default;

  $headings: h1, h2, h3, h4, h5, h6;
  $size: $h1, $h2, $h3, $h4, $h5, $h6;

  $heading-size: zip($headings, $size);
  
  #{headings()} {
    margin: 10px 0;
    line-height: 1.5em;
  }

  @each $h in $heading-size {
    #{nth($h, 1)} {
      font-size: nth($h, 2);
    }
  }
```

**Comment by anthonydillon** [comment]
Lets chat about this method in our dev-catch up on weds. The code above is not compiling in sassmeister.

**Comment by richmccartney** [comment]
@anthonydillon Ah yeah it won't as there are a few variables missing but I have it working on another project.

**Comment by anthonydillon** [comment]
@richmccartney It's good but would need to be extended to handle font-weight, margin-bottom, text-transform, etc.

Refer to our current styles: https://github.com/ubuntudesign/vanilla-framework/blob/master/scss/modules/_typography.scss#L192

**Comment by anthonydillon** [comment]
@richmccartney I really like this approach and now that we have sign off on heading styles this would be great to get working. Could you spend sometime and get this into Vanilla?

**Comment by richmccartney** [comment]
@anthonydillon yeah sure, I'll look into it again and do something which adds the class names as well.

**Comment by yaili** [comment]
@richmccartney Is this related to #234 ?
