### ISSUE TITLE
Second level nav not vertically centered

### ISSUE THREAD

**Issue by anthonydillon** [ubuntudesign/vanilla-framework#227]
If someone used vanilla-framework with a breadcrumb navigation the links are closer to the top of the box then the bottom. They should be the same.

![vanilla framework pattern library](https://cloud.githubusercontent.com/assets/1413534/9622556/5e981c60-512c-11e5-80c3-e60d60fa1447.png)

**Comment by anthonydillon** [comment]
Chevrons are also to close to the link item on the left

**Comment by barrymcgee** [comment]
Resolved by #229
