### ISSUE TITLE
Should buttons have transition on them?

### ISSUE THREAD

**Issue by anthonydillon** [ubuntudesign/vanilla-framework#228]
Currently buttons hover colours are instant. There are instances of a transition (insights, jujucharms, etc) from one background colour to another.

**Comment by deadlight** [comment]
I'm broadly in favour of these sorts of changes that would make the feel of vanilla a little more rich.

**Comment by richmccartney** [comment]
I was thinking about animations 
Regards,

Richard McCartney
Front End Web Developer
Cloud & Web Team

richard.mccartney@canonical.com <mailto:richard.mccartney@canonical.com>
+44 (0) 792 183 4505

**Comment by richmccartney** [comment]
I was thinking about animations and I think we need to have a constant feel between them all. Some style guides will show the time and interaction taken with an animation / transition and all would have a constant feel in timing. We should look at this and have a library of pre made transitions or keyframes to apply to any state of hover or focus we require.
Regards,

Richard McCartney
Front End Web Developer
Cloud & Web Team

richard.mccartney@canonical.com <mailto:richard.mccartney@canonical.com>
+44 (0) 792 183 4505

**Comment by yaili** [comment]
The transition speed in Juju feels a bit slow, but I would us to explore this.

**Comment by barrymcgee** [comment]
See #191 for update.

**Comment by pmahnke** [comment]
added transition: background-color .2s;
