### ISSUE TITLE
Inner wrapper width override not working

### ISSUE THREAD

**Issue by richmccartney** [ubuntudesign/vanilla-framework#230]
When trying to override $site-max-width in a new theme global settings it doesn't seem to effect ```.inner-wrapper``` in ```_grid.scss```.

**Comment by anthonydillon** [comment]
The inner-wrapper gets `max-width: $site-max-width;` do you not see that? https://github.com/ubuntudesign/vanilla-framework/blob/master/scss/modules/_grid.scss#L58

**Comment by yaili** [comment]
@richmccartney Has this been answered?

**Comment by barrymcgee** [comment]
Will be addressed by #387
