### ISSUE TITLE
Add search to demo

### ISSUE THREAD

**Issue by anthonydillon** [ubuntudesign/vanilla-framework#232]
We have a search module which is not utilised in the demo. Please add.

**Comment by nottrobin** [comment]
So there is an `<input type="search">` on the demo page in the [forms section](http://ubuntudesign.github.io/vanilla-framework/demo/#forms), but it doesn't use any of the search classes.

I tried adding `class="search-form"` to the form that wraps the search field, and then the search field appears floated to the right, which looks a little odd:

![search floats right](http://i.imgur.com/c7jrug1.png)

And on a thinner screen, it disappears completely:

![search disappears](http://i.imgur.com/DvByRIA.png)

Should we fix search a bit before we try to demo it?

**Comment by anthonydillon** [comment]
I meant to add the search module in the header as its part of it. Nice idea to add to the list of components but its quiet tied into the header and navigation so I think its fine to just add it up there for now.
