### ISSUE TITLE
Create tooltip styles and markup

### ISSUE THREAD

**Issue by richmccartney** [ubuntudesign/vanilla-framework#233]
Port from Juju / MAAS tool tip styles using CSS3 and Data attributes for content.

**Comment by yaili** [comment]
Example when hovering over the charm icons under "Connects to:" https://jujucharms.com/ceph/

**Comment by anthonydillon** [comment]
Yes. Do we need this functionality in Vanilla or is it to advanced?

**Comment by yaili** [comment]
I don't think it's too advance.

**Comment by anthonydillon** [comment]
Ok sure, happy to go with the juju tooltip style?

**Comment by yaili** [comment]
Yes.

**Comment by yaili** [comment]
We agreed we'd add tooltips to cloud theme for now. @anthonydillon Were they added to Vanilla?

**Comment by anthonydillon** [comment]
No they are only in the cloud Vanilla theme.

**Comment by yaili** [comment]
OK, in that case I'm closing this for now.
