### ISSUE TITLE
Look at improving header styles

### ISSUE THREAD

**Issue by richmccartney** [ubuntudesign/vanilla-framework#234]
When creating a new header style for MAAS vanilla GUI I found it quite frustrating to override the visual style of the header. To do this you would need to understand the whole way we have built the section and found it was quite daunting to change everything I needed.

My solution is to split out each part of the header in its own respective mixins. These mixins would contain all variables which hold the sizing and colours required for the header.

This also would give the option to remove a section of the header and completely make your own.

**Comment by yaili** [comment]
@richmccartney How does this relate to #352 ?

**Comment by barrymcgee** [comment]
This will be addressed when we review all current patterns and whether or not they are still fit for purpose. I think there's a general consensus that the current header pattern is too Ubuntu-opinionated and too specific making an extending further downstream too difficult.

**Comment by anthonydillon** [comment]
I would love to see the header simplified and optimised sooner rather then
later as it is very messy. The longer this is left the more people will be
put off by the overly styled and selected header.
