### ISSUE TITLE
Add <article> to vertical divider & equal heights

### ISSUE THREAD

**Issue by richmccartney** [ubuntudesign/vanilla-framework#235]
Felt this is a missing container we need for both modules.

**Comment by anthonydillon** [comment]
This will end up spiraling out of control with the number of elements to
add. I think we should maintain the supported elements and add a BEM class
to target the child elements if not a div or li.

**Comment by deadlight** [comment]
I agree, we should make the CSS element agnostic; especially for these sort of helper classes.

**Comment by barrymcgee** [comment]
This issue is now invalid.
