### ISSUE TITLE
Showing numbers instead of quotation marks and nav chevron (Chrome)

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/vanilla-framework#236]
Instead of the quotation marks and the nav chevron, I see the numbers 8 and 9.

**Comment by anthonydillon** [comment]
@yaili is this still an issue http://ubuntudesign.github.io/vanilla-framework/demo/

**Comment by yaili** [comment]
No.

**Comment by anthonydillon** [comment]
Thanks, we fixed the font issue a while back in Vanilla I just wanted to make sure.
