### ISSUE TITLE
Vertical divider lines should go all the way to the bottom of the block

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/vanilla-framework#237]
This isn't happening in both with divs and with lists examples.

**Comment by richmccartney** [comment]
I've noticed I have had to combine ```.equal-heights``` with this class to make it work. Could possibly see these two being apart of the same module with correct BEM classes to amend any styling.

**Comment by anthonydillon** [comment]
We just did this with align-vertically class so I'm :+1: with this feature

**Comment by deadlight** [comment]
vertical-divider relies on being used with equal-height in all use-cases, that's another :+1: from me
