### ISSUE TITLE
We need to test contrast and visibility in input messages

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/vanilla-framework#238]
We need to test contrast and visibility in the input warning/information/success/error messages in forms.

**Comment by barrymcgee** [comment]
Both our positive and warning colours​ in the palette fail AA on white;

**Comment by yaili** [comment]
The warning colour is used with #333

**Comment by yaili** [comment]
Sorry, I thought this was referring to notifications. Form notifications should be flagged for an update.
