### ISSUE TITLE
Add styles for text elements that follow other text elements

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/vanilla-framework#241]
We should have styles for:
* headings that follow headings
* paragraphs that follow headings
* lists inside lists
* lists that follow paragraphs
* and vice versa to everything

**Comment by anthonydillon** [comment]
@yaili could you provide a design pattern for these?

**Comment by barrymcgee** [comment]
These should be addressed in turn when we sweep through in prep for v1. Leaving this issue here for posterity so we can cross-reference nearer that time to ensure all bases have been covered.

**Comment by yaili** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;q3Z1Eikq&#x2F;1494-define-styles-for-text-elements-that-follow-other-elements"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Define styles for text elements that follow other elements</a>

**Comment by barrymcgee** [comment]
Base typography styles now include the following;

**Comment by yaili** [comment]
OK, thanks. We might need to add more in the future, but for now let's mark this closed.
