### ISSUE TITLE
What does row .no-border do?

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/vanilla-framework#244]
Does it remove all borders? Or just some?

**Comment by richmccartney** [comment]
@yaili It removes all borders. I have an idea for all box model layers where we can do something like ```.no-border``` to remove all borders or ```.no-border--top```. Second class would remove just the top border and we could replicate this pattern for padding and margins. See https://github.com/ubuntudesign/maas-gui-vanilla-theme/blob/master/scss/generic/_helpers.scss for example as I plan to bring this into Vanilla core.

**Comment by barrymcgee** [comment]
@yaili Has this question been addressed? If so, can you please close this ticket :)

**Comment by yaili** [comment]
@barrymcgee This one in specific has, but I think we need another one to address these names as they don't seem very intuitive.

**Comment by barrymcgee** [comment]
@yaili Hopefully adoption of BEM across the framework should address this.
