### ISSUE TITLE
What does .med-six-col do?

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/vanilla-framework#246]

**Comment by barrymcgee** [comment]
@yaili From the comments in the codebase;

```
// Med-six-col is a wrapper for a group three-cols.
// It converts the three-cols to six-cols in medium viewports
```

It basically caters for the use case where 3 columns would be too tight on a ~tablet screen so it makes the layout 2-col. 

The layout then reverts to 3 columns at the large breakpoint. (currently 1030px)

**Comment by yaili** [comment]
I just looked at this again, the demo shows 4-cols. Why?

http://ubuntudesign.github.io/vanilla-framework/demo/

@anthonydillon

**Comment by yaili** [comment]
I'm confused.

**Comment by yaili** [comment]
So basically it's for a four column layout?

**Comment by anthonydillon** [comment]
Only medium screens four `.four-cols` would be squeezed. If wrapped in `.med-six-col` they will become stack 2 on 2 so basically use six-col styles.
