### ISSUE TITLE
Helper classes .left and .right need clearing in small screen

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/vanilla-framework#252]
Notice the border below them doesn't have space around it

**Comment by richmccartney** [comment]
Just a thought on top of this bug, I feel the class names ```.left``` or ```.right``` is to vague. Going with the new BEM approach would we feel it would be far more beneficial to rename these classes along the lines of ```.float--left  .float--right  .float--none```.

Thoughts?

**Comment by yaili** [comment]
Agree.

**Comment by anthonydillon** [comment]
:+1:

**Comment by yaili** [comment]
@anthonydillon @richmccartney Should this be separated into two bugs?

**Comment by anthonydillon** [comment]
No I think one bug is fine.

**Comment by barrymcgee** [comment]
This will be swept up when we review all current utils and BEMify the code.

**Comment by anthonydillon** [comment]
What about the utility name space? `u-float--right`, etc.

**Comment by barrymcgee** [comment]
@anthonydillon We'll discuss this next week in our code re-structure meeting but I imagine we'll need a small collection of immutable utility classes.
