### ISSUE TITLE
border intersections in tables mis-align in firefox

### ISSUE THREAD

**Issue by codersquid** [ubuntudesign/vanilla-framework#257]
The table borders in firefox have an alignment problem at the border intersections. This happens inconsistently but frequently. The pixels at the intersections have pixels that go above or below the pixels being crossed over. In Chrome, the border intersects in one dot.

![alignment-dots](https://cloud.githubusercontent.com/assets/529748/11373372/a2620e36-9297-11e5-9a51-8e443e697fc5.png)

Build identifier: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:42.0) Gecko/20100101 Firefox/42.0

**Comment by barrymcgee** [comment]
@codersquid - thank you for taking the time to raise this issue and please accept my apologies for the delay in getting back to you.

We are currently working on a `v1` release of Vanilla Framework which involves visually overhauling the majority of the patterns. As a result, the default table pattern no longer has a dotted border making this issue now obsolete.
