### ISSUE TITLE
Code needs line-height on all viewports

### ISSUE THREAD

**Issue by anthonydillon** [ubuntudesign/vanilla-framework#258]
Currently the code styling the line-height is inside a media query. This needs to be applied all the time.

**Comment by anthonydillon** [comment]
As part of this improvement. Code blocks would benefit from a margin-bottom also.

![benchmarking with juju](https://cloud.githubusercontent.com/assets/1413534/11422546/9b3c1766-9434-11e5-9b09-7d2c0dc21433.png)

**Comment by barrymcgee** [comment]
Addressed by #370
