### ISSUE TITLE
[IE8] Grid does not work

### ISSUE THREAD

**Issue by anthonydillon** [ubuntudesign/vanilla-framework#263]
![dashboard](https://cloud.githubusercontent.com/assets/1413534/11873974/2cca91fc-a4d5-11e5-9cea-8ddc63eed621.png)

**Comment by barrymcgee** [comment]
We can review this again once we have defined our browser support matrix.

**Comment by anthonydillon** [comment]
I feel this one is worth the effort of investigating as it's a large breaking issue on older browsers. I think we can do better here to be progressive.
