### ISSUE TITLE
[iPhone 6 - iOS] Submit input is not styled correctly

### ISSUE THREAD

**Issue by anthonydillon** [ubuntudesign/vanilla-framework#264]
![bs_realios_mobile_iphone 6-8 0](https://cloud.githubusercontent.com/assets/1413534/11877297/58a7218a-a4e6-11e5-9dae-bf4bd167f7c5.jpg)

**Comment by yaili** [comment]
This still an issue.

**Comment by barrymcgee** [comment]
Now resolved...

![img_9858](https://cloud.githubusercontent.com/assets/505570/18308795/0066c664-74ee-11e6-812f-45977b8dbaa6.PNG)

**Comment by yaili** [comment]
The issue was with input type=submit. Is this fixed?

**Comment by barrymcgee** [comment]
Yes - input type=submit no longer applies iOS default styling. Fixed.
