### ISSUE TITLE
[Nexus 7] Back to top not positioned correctly

### ISSUE THREAD

**Issue by anthonydillon** [ubuntudesign/vanilla-framework#270]
Both are not right. See below:
![bs_realdroid_tablet_google nexus 7-4 4-1200x1920](https://cloud.githubusercontent.com/assets/1413534/11877810/789170b0-a4e9-11e5-83bf-a915e461febe.jpg)

**Comment by yaili** [comment]
Still valid.

**Comment by yaili** [comment]
Tested on Browserstack and look fixed.
