### ISSUE TITLE
[Nexus 7] Landscape back to top issue

### ISSUE THREAD

**Issue by anthonydillon** [ubuntudesign/vanilla-framework#271]
![bs_realdroid_tablet_google nexus 7-4 4-1200x1920 1](https://cloud.githubusercontent.com/assets/1413534/11877862/e240acba-a4e9-11e5-8603-8ae893af1f5c.jpg)

**Comment by barrymcgee** [comment]
Similar to #270

**Comment by yaili** [comment]
Still valid.

**Comment by yaili** [comment]
@anthonydillon Do you mean landscape instead of portrait?

**Comment by anthonydillon** [comment]
Yes sorry. Will update the title.

**Comment by yaili** [comment]
Tested on Browserstack and look fixed now.
