### ISSUE TITLE
Add code snippets style

### ISSUE THREAD

**Issue by anthonydillon** [ubuntudesign/vanilla-framework#290]
Currently the logic behind the background colour of code snippets is a lighter version of the brand color. This works for Ubuntu as it gives us the correct light orange but in the case of Canonical it makes the code snippets light pink. 

Should we sent the background to a set colour or if there something clever we can do with the brand colour in all situations?

We have a new code style now on Ubuntu and Cloud which have a purple background. Should we use that?

**Comment by yaili** [comment]
Yes, let's use the new style.

**Comment by yaili** [comment]
I've found two different styles for the default pre tag:
<img width="616" alt="screen shot 2016-02-19 at 14 16 34" src="https://cloud.githubusercontent.com/assets/223966/13568321/6b8a9db6-e458-11e5-9896-bc5e466d167c.png">
<img width="614" alt="screen shot 2016-02-19 at 14 17 08" src="https://cloud.githubusercontent.com/assets/223966/13568326/6f86c214-e458-11e5-9bb2-23cbd27fbe1f.png">

I'm assuming the black version is the latest one, so we should incorporate that in Vanilla. /cc @Lucapaulina

**Comment by anthonydillon** [comment]
This is the latest code snippet design:
![get started juju](https://cloud.githubusercontent.com/assets/1413534/13571210/58e9d9f2-e46b-11e5-8326-c253977f7627.png)

**Comment by richmccartney** [comment]
I think they should all be reviewed. We don't have a definitive code block style as well. We need to add the copy style to them and maybe code line numbers as well.

**Comment by Lucapaulina** [comment]
The black style is the latest one for code. We use the example Ant linked
for short snippets but not code blocks.

**Comment by richmccartney** [comment]
Yeah on MAAS we have large code blocks for YAML and XML output. These all have code line numbers similar to GigHub

**Comment by yaili** [comment]
Agreed at off-site:

- **.code**: < code > element (Vanilla)
- **.code-block**: white/light with numbers (Vanilla)
- **.code-block--terminal**: dark (Vanilla)
- **.code-snippet**: white/light with copy-to-clipboard (Vanilla)
- **.code-snippet--terminal**: dark with copy-to-clipboard (Vanilla)

**Comment by yaili** [comment]
@anthonydillon Has this been done?

**Comment by anthonydillon** [comment]
No, the code snippets just have mono font at the moment.

**Comment by yaili** [comment]
@anthonydillon You're assigned to this bug. Are you working on this, or should it be re/de-assigned?

**Comment by anthonydillon** [comment]
Unassign please. Not sure why I was assigned.

**Comment by dholbach** [comment]
This would be super important to us in the Community team, as we'd like to adopt this for developer.ubuntu.com.

**Comment by dholbach** [comment]
Are you going to support different programming languages and markup in the `<code>` blocks?

**Comment by deadlight** [comment]
That's definitely something to aim for but, initially, we just need to standardise our current usage.

**Comment by dholbach** [comment]
I just learned from @caldav that we're using a different piece of code for programming languages, etc. Still having this bug fixed would help us a lot in a future move to Vanilla.

**Comment by barrymcgee** [comment]
Fixed by #370

**Comment by dholbach** [comment]
Nice one!
