### ISSUE TITLE
No documentation for row-hero

### ISSUE THREAD

**Issue by anthonydillon** [ubuntudesign/vanilla-framework#291]
Row-hero is missing documentation.

- Go to http://ubuntudesign.github.io/vanilla-framework/docs/ 
- Search for "row-hero" and it returns nothing
- Go to the row section [1] and see there is no mention of row-hero

[1] http://ubuntudesign.github.io/vanilla-framework/docs/#rows-mixin-vf-rows

**Comment by barrymcgee** [comment]
`.row-hero` has been deprecated in `v1-dev`
