### ISSUE TITLE
Grid is lacking documentation

### ISSUE THREAD

**Issue by anthonydillon** [ubuntudesign/vanilla-framework#293]
The grid component is missing documentation and examples in the docs. There should be a mention of the append and prepend functionality.Maybe even split them out into there own sub-mixins of the grid.

**Comment by yaili** [comment]
Do you mean it's missing form the style guide doc? There are examples in design.ubuntu.com/web, I've added them to the new vanilla style guide too.

**Comment by anthonydillon** [comment]
Sorry I mean in code documentation so it should if the compiled docs

**Comment by yaili** [comment]
OK.
