### ISSUE TITLE
Add "Please upgrade your browser" messages?

### ISSUE THREAD

**Issue by nottrobin** [ubuntudesign/vanilla-framework#296]

**Comment by anthonydillon** [comment]
Huh? Really?

**Comment by nottrobin** [comment]
It was just a suggestion. Maybe, maybe not. Maybe it belongs in individual sites rather than in vanilla. But I was just reviewing Karl's ie8 fixes in canonical-website. You can read the content, but the site looks horrible. I assume it's the same for all our sites. If we're not committing to trying to make the site look nice in a browser cos it's too old, isn't it helpful to say so?

**Comment by anthonydillon** [comment]
If older browsers are not supported by Vanilla that is a limitation of the framework and not a fault of the user. A lot of people using older browsers have no choice but to use them. As they could be in an institution which they have no rights to update software or on a machine with an old OS.

I do believe this raises a good point. We should define our browser support matrix and display it prominently on the project page and README. This will provide external users of Vanilla the information to decide if they want to use the framework.

We should make all efforts to improve the support of older browsers until it acts to hider future development. If there are fixes we can land we should. And by performing the IE8 testing there should be some back portable fixes into Vanilla.

**Comment by nottrobin** [comment]
Yep agreed on all of that. Most people probably do have no choice in the software they use, and we don't want to insult or condescend to them.

However, we're not realistically going to meaningfully support ie8, and I don't think we should. So I don't see what's wrong with a friendly non-judgmental & subtle note explaining why the site looks so shit. Maybe some autonomous XP users out there didn't realise that Chrome of Firefox would offer a much better experience.

**Comment by nottrobin** [comment]
But I do think probably vanilla isn't the place for such a message. So we'll have the discussion about individual sites elsewhere. I'll close this.
