### ISSUE TITLE
Remove opacity from placeholder styles

### ISSUE THREAD

**Issue by anthonydillon** [ubuntudesign/vanilla-framework#298]
We should style the placeholders opacity at the theme level as its difficult to override and a lot of the time we require opacity: 1.

**Comment by richmccartney** [comment]
I think we shouldn't use an opacity at all, maybe have a ```$placeholder``` variable which will hold the colour instead.

**Comment by yaili** [comment]
@anthonydillon @richmccartney Has this been decided? Is it an enhancement?

**Comment by anthonydillon** [comment]
I think we should use solid colours help contrast in inputs to help
accessibility.

**Comment by barrymcgee** [comment]
@richmccartney Has this been resolved by your form work?
