### ISSUE TITLE
Select form elements are missing styles

### ISSUE THREAD

**Issue by anthonydillon** [ubuntudesign/vanilla-framework#300]
The missing styles are:
```css
select {
    font-size: 1em;
    font-weight: 300;
}
```

**Comment by richmccartney** [comment]
We should apply the pattern style to the select with an added chevron background image, similar to line 80 in [_components.forms.scss](https://github.com/ubuntudesign/maas-gui-vanilla-theme/blob/master/scss/_components.forms.scss).

**Comment by yaili** [comment]
@anthonydillon Has this been done? Bug?

**Comment by anthonydillon** [comment]
This has not been done yet but is an enhancement.
