### ISSUE TITLE
Grid missing .col

### ISSUE THREAD

**Issue by anthonydillon** [ubuntudesign/vanilla-framework#301]
The old grid had a class of `col` which applied all the column styles but with 100% width. Is it used sporadically from site to site so we should add it back in.

Guidelines implantation: http://bazaar.launchpad.net/~canonical-webmonkeys/ubuntu-web-style-guide/trunk/view/head:/sass/responsive/latest/_core-grid.scss#L54

**Comment by yaili** [comment]
@anthonydillon Has this been done? Is it a bug?

**Comment by anthonydillon** [comment]
Still required and is a bug.

**Comment by anthonydillon** [comment]
`.twelve-col` does the trick.
