### ISSUE TITLE
Headings in stepped-list don't align properly if using h4s instead of h3s

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/vanilla-framework#302]
When I use an h4 instead of an h3, the heading moves a few pixels to the left, compared to using an h3, so it doesn't align with paragraph text below anymore.

**Comment by richmccartney** [comment]
@yaili can you add a screenshot just showing what happens?

**Comment by yaili** [comment]
<img width="243" alt="stepped-list" src="https://cloud.githubusercontent.com/assets/223966/13178889/16e0e302-d719-11e5-8d44-0023320cd33a.png">
