### ISSUE TITLE
Missing disabled button style

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/vanilla-framework#303]
I can't find a button--disabled style in the demo. Is there one?

**Comment by richmccartney** [comment]
There isn't one currently in the framework but we should also add ```disabled="disabled"``` into the mix. It's more likely a lot of forms will use that format to disable any form elements.

**Comment by yaili** [comment]
Yes, that too. What about the coming soon button here? http://www.ubuntu.com/phone/devices
