### ISSUE TITLE
Default radio button has a grey square background

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/vanilla-framework#304]
This seems to be added by the box shadow, which doesn't seem to be necessary. [Chrome]

**Comment by yaili** [comment]
Same happens in the disabled radio button.

**Comment by richmccartney** [comment]
Should we look to actually style both the checkbox and radio buttons, similar to what has been done from line 136 on [_components.forms.scss](https://github.com/ubuntudesign/maas-gui-vanilla-theme/blob/master/scss/_components.forms.scss).

**Comment by yaili** [comment]
Is there a live demo?

**Comment by anthonydillon** [comment]
Just http://ubuntudesign.github.io/vanilla-framework/demo/#forms.

**Comment by yaili** [comment]
I meant for what Richard said.

**Comment by richmccartney** [comment]
@yaili @anthonydillon I've added a demo of the MAAS GUI [here](http://ubuntudesign.github.io/maas-gui-vanilla-theme/index.html).

**Comment by yaili** [comment]
Cool, thanks!

**Comment by richmccartney** [comment]
I will remove any styling on the checkboxes and the radio buttons. After talking with @yaili we both agree'd it would be better to just keep these styles as intended from the OS / browser.
