### ISSUE TITLE
Improve file structure

### ISSUE THREAD

**Issue by richmccartney** [ubuntudesign/vanilla-framework#305]
With the new style guide underway we might need to consider a slight shift in our file structure. I can see this having a few benefits such as better structure on what is what. Currently having everything as a 'module' doesn't really explain what the the files contain.

If we were to change the structure we could use the [style guide matrix](https://docs.google.com/spreadsheets/d/17P7ncqfhZHPPClZZuWxwZaJIszeBiYC6ujH8NMUbpbM/edit?ts=56b0da3c#gid=0) as reference.

This would mean either moving all files in respective folders such as base, components, helpers e.t.c or prefixing all file names with what type of contents they have e.g _settings.defaults.scss, _components.forms.scss and _pattern.navigation.scss.

I have moved [MAAS GUI](https://github.com/ubuntudesign/maas-gui-vanilla-theme/tree/master/scss) into one of the proposed ways as an example. What are our thoughts on this?

**Comment by anthonydillon** [comment]
I like this idea! I think we should defo split our layout styles from our
components.

When it comes to folder vs files with dots. I'm not sure, but since looking
through the MAAS stuff its easy to navigate and see where stuff is without
jumping in and out.

**Comment by barrymcgee** [comment]
After our meeting today we've decided to proceed with a [ITCSS](https://speakerdeck.com/dafed/managing-css-projects-with-itcss) way of thinking while naming files in a flat structure like the MAAS example above - e.g. `_base.grid.scss`

This will land with `v1.0`
