### ISSUE TITLE
Consider including ubuntu (and canonical) pull quote colours to Vanilla

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/vanilla-framework#314]
## Context

Currently in Vanilla we only have the grey coloured pull quotes (there is another bug to correct the grey).

I think we should include all colour variants that we have in Vanilla. From what I can see, Canonical also uses the orange version.

I'm assuming this would mean renaming the classes or adding modifiers?

Let's discuss.

**Comment by anthonydillon** [comment]
The problem with including the ubuntu and canonical colours in the framework is that they will be present in cloud or any other theme which would make the colours redundant. I think the best place for these colours would be in the themes that require them.

**Comment by yaili** [comment]
From what I can see, we're using orange quotation marks on both canonical and ubuntu.

**Comment by yaili** [comment]
#242 This has been captured on this issue.
