### ISSUE TITLE
Find a way to dynamically load pictograms

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/vanilla-framework#315]
## Context

It would be good to show the pictograms that can be used across our sites all at once. But it would be too cumbersome to do this manually.

## Expected result

Can we find a way to get list of pictograms onto our documentation/style guides easily?

**Comment by anthonydillon** [comment]
I'm not sure including pictograms in Vanilla is a good idea. We currently have no assets in this project and only show some necessary icons with inline svgs so it works offline.

**Comment by yaili** [comment]
I don't mean including in vanilla per se. But I'd like to show them in the style guides.

**Comment by anthonydillon** [comment]
I wonder if we should create a style guide repo to put content and issues?
Instead of creating none Vanilla issues here.

**Comment by yaili** [comment]
You're right. I'll just move this one to the other project.
