### ISSUE TITLE
What is the role of video-container?

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/vanilla-framework#317]
What does this class do?

**Comment by anthonydillon** [comment]
Too be added to a div wrapping a video. For example: http://ubuntudesign.github.io/vanilla-framework/docs/#helpers-mixin-vf-video-container

**Comment by yaili** [comment]
How is it different from a normal div?

**Comment by anthonydillon** [comment]
By wrapping a video embed like youtube it makes the video responsive.
