### ISSUE TITLE
Vertically align is centering text

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/vanilla-framework#322]
## Context

When vertically-align is applied to a text block (instead of the to the usual image block), it centres the text.

## Expected result

The text should stay left aligned.

**Comment by yaili** [comment]
@grahambancroft @anthonydillon Has this been looked at?

**Comment by anthonydillon** [comment]
Not by me, hopefully someone on a bug Friday can take some time to look
into this.

**Comment by grahambancroft** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;rYhv8AsB&#x2F;1176-vertically-align-is-centering-text-322"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Vertically align is centering text #322</a>
