### ISSUE TITLE
Update reset

### ISSUE THREAD

**Issue by anthonydillon** [ubuntudesign/vanilla-framework#324]
Normalize 4.0.0 is finally here and with that we should update the reset.

https://github.com/necolas/normalize.css

**Comment by yaili** [comment]
@anthonydillon Is this an enhancement or refactoring?

**Comment by anthonydillon** [comment]
Just a dependency update so maintenance I think.

**Comment by yaili** [comment]
@anthonydillon There is no such label. Shall I create it?

**Comment by anthonydillon** [comment]
I think so.
