### ISSUE TITLE
Headings on small screens are to large

### ISSUE THREAD

**Issue by anthonydillon** [ubuntudesign/vanilla-framework#331]
As we no longer reduce the base font size we need to effect the `font-size` of headings on small screens at the same ratio of >1030px 15px base font size and  >768px 14px base font size.

**Comment by yaili** [comment]
The font sizes at medium and small screens are not just a percentage smaller than large screens, otherwise the headings would be too large, so they were adjusted.

From what I can see on ubuntu.com:

Small screen:

- h1. 22.75px
- h2. 20px
- h3. 17px
- h4. 17.5px (this sounds wrong, but it's on ubuntu.com)
- h5. 14px, bold 
- h6. 10px, weigth 400, uppercase, letterspacing 1px
- p. 14px

Medium screen:

- h1. 24.5px
- h2. 21.5px
- h3. 18px
- h4. 18.75px, weight 400 (again, not great)
- h5. 15px, weight 700
- h6. 10.85px, weight 400, uppercase, letterspacing 1px

**Comment by pmahnke** [comment]
![image](https://cloud.githubusercontent.com/assets/441217/14404055/68511bda-fe65-11e5-94b5-8af353018311.png)

Interesting... what my computed fix is:

* h1. 2.46094em, 39.375px
* h2.1.75em, 28px
* h3. 1.25781em, 20.125px
* h4. 1.09375em, 17.5px, weight 400
* h5. 0.875em, 14px, weight 700
* h6. 0.71094em, 11.375px, weight 400, letter-spacing .1em, uppercase

How do you want to move forward?  I think that h1 looks especially small on the phone

**Comment by yaili** [comment]
I think we should keep the current small and medium screen scale on ubuntu.com. It doesn't have to be updated in Vanilla, but the headings are currently too large.

**Comment by pmahnke** [comment]
@yaili @anthonydillon 

I am not getting Yaili's numbers for medium on ubuntu.com

If I use @yaili's I get

![image](https://cloud.githubusercontent.com/assets/441217/14405880/e7dc5790-fe90-11e5-8319-3a8eaad21dad.png)

    h1 {
      font-size: 1.531em;
      margin-bottom: .5em;
    }

    h2 {
      font-size: 1.344em;
      margin-bottom: .5em;
    }

    h3 {
      font-size: 1.125em;
      margin-bottom: .522em;
    }

    h4 {
      font-size: 1.172em;
      font-weight: 400;
      margin-bottom: .615em;
    }

    h5 {
      font-size: .938em;
      font-weight: 700;
      margin-bottom: 1em;
    }

    h6 {
      font-size: .678em;
      font-weight: 400;
      margin-bottom: 1em;
      letter-spacing: .1em;
      text-transform: uppercase;
    }


if I use ubuntu.com, I get

![image](https://cloud.githubusercontent.com/assets/441217/14405883/fe94984e-fe90-11e5-9dbb-04adc1ae0fb2.png)

h1 {
    font-size: 1.625em;
    margin-bottom: .5em;
}

h2 {
    font-size: 1.438em;
    margin-bottom: .5em;
}

h3 {
    font-size: 1.219em;
    margin-bottom: .522em;
}

h4 {
    font-size: 1.25em;
    font-weight: 400;
    margin-bottom: .615em;
}

h5 {
    font-size: 1em;
    font-weight: 700;
    margin-bottom: 1em;
}

h6 {
    font-size: .723em;
    font-weight: 400;
    margin-bottom: 1em;
    letter-spacing: .1em;
    text-transform: uppercase;
}

Yaili's are a bit smaller than my ubuntu.com numbers... what do you want me to do?

Peter

**Comment by yaili** [comment]
I'd replicate Ubuntu.com
