### ISSUE TITLE
Secondary nav: hover state not working (should be $link-colour)

### ISSUE THREAD

**Issue by nottrobin** [ubuntudesign/vanilla-framework#334]
There is no hover state applied to links in the `second-level-nav`, even though links in the `third-level-nav` have a hover state of `color: $link-color;`.

https://github.com/ubuntudesign/vanilla-framework/blob/master/scss/modules/_breadcrumbs.scss#L167

I believe `second-level-nav` should also have the same rule applied.

**Comment by nottrobin** [comment]
For now this is being fixed directly in www.ubuntu.com: https://github.com/ubuntudesign/www.ubuntu.com/issues/257 (private link).

When we come to address this bug we should decide what to do with the local www.ubuntu.com fix (probably remove it).

**Comment by yaili** [comment]
@nottrobin Is this bug closed?

**Comment by barrymcgee** [comment]
Secondary nav has been deprecated from the header pattern in `v1-dev`
