### ISSUE TITLE
Should equal-height__align-vertically have align-items: center?

### ISSUE THREAD

**Issue by nottrobin** [ubuntudesign/vanilla-framework#336]
`equal-height__align-vertically` seems to *horizontally* align items as well, with `align-items: center`. This is causing problems like this: https://github.com/ubuntudesign/www.ubuntu.com/issues/153 (private).

Should this rule be removed?

**Comment by anthonydillon** [comment]
Correct. Vertically centre should do just that and allow the flexibility of
using the utility class align-centre.

**Comment by yaili** [comment]
@anthonydillon @nottrobin Is this a bug or an enhancement?

**Comment by anthonydillon** [comment]
Bug.
