### ISSUE TITLE
Provide offline fonts

### ISSUE THREAD

**Issue by anthonydillon** [ubuntudesign/vanilla-framework#341]
We need to work out a way to embed the Ubuntu font without loading it from assets. We need to remove the asset and server paths as vanilla should be completely offline. I wonder if base64 could be a solution.

**Comment by yaili** [comment]
@barrymcgee Are you working on this?

**Comment by yaili** [comment]
@barrymcgee Shall I remove your name from it, then?

**Comment by anthonydillon** [comment]
I'm not sure this is required of Vanilla. If someone needs offline fonts
they should download and host them with the sites assets. The asset path is
a variable that is easily modified locally.

This is what I did for Juju GUI.

**Comment by yaili** [comment]
@anthonydillon But you filed the issue :)

**Comment by anthonydillon** [comment]
Yes that was before I worked out this method. Can close.
