### ISSUE TITLE
Build tabs pattern

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/vanilla-framework#347]
## Context

Tabs are inconsistent across sites/themes. We agreed at off-site to use the current MAAS style to Vanilla, but they need some design work/workshop.

**Comment by yaili** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;zLHqPtrh&#x2F;1496-define-tabs-style"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Define tabs style</a>

**Comment by yaili** [comment]
MAAS and Juju seem to be using similar tabs pattern. Vanilla will use the same, but the selected tab will be highlighted in cool grey. Design to follow.

**Comment by barrymcgee** [comment]
@yaili If possible before next week can you add the designs to this ticket?

**Comment by yaili** [comment]
@barrymcgee will this work? https://github.com/ubuntudesign/vanilla-design/tree/master/Tabs
