### ISSUE TITLE
Should we add a .compact-box on cloud theme?

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/vanilla-framework#348]
This was a question raised for discussion at the off-site. We need to address it at some point.

**Comment by anthonydillon** [comment]
Sorry could someone refresh my memory on what a .compact-box is? Was it the
boxed list?

**Comment by yaili** [comment]
I think it was a box with less padding.

**Comment by barrymcgee** [comment]
Given we've now deprecated `.box` for `.card` and this question also relates to the cloud theme - I'm going to close off this issue.
