### ISSUE TITLE
Define default definition list style

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/vanilla-framework#350]
From the off-site:

- [x] Compare Juju and MAAS DL
- [x] Potentially MAAS's style can be the default DL, and Juju's a variation (as it has indentation)

**Comment by yaili** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;xnMTLJuO&#x2F;1497-define-definition-list-style"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Define definition list style</a>

**Comment by yaili** [comment]
The Vanilla definition list should follow the current Juju style.

**Comment by barrymcgee** [comment]
@yaili I don't know what the current Juju style is. For the avoidance of doubt, can you explicitly add design specs to the relevant issue so we're both on the same page :)

**Comment by spencerbygraves** [comment]
@barrymcgee you can see it at the bottom of our charm details pages:

http://demo.jujugui.org/?store=trusty/wordpress

**Comment by yaili** [comment]
@spencerbygraves thank you

**Comment by barrymcgee** [comment]
That link is a 503 :(

**Comment by yaili** [comment]
Any charm page should have one at the bottom.
