### ISSUE TITLE
Add heading classes

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/vanilla-framework#352]
We agreed to include the classes from **.heading-1** through to **.heading-6** to Vanilla.

**Comment by barrymcgee** [comment]
This is a separate issue to #234

**Comment by yaili** [comment]
Apparently these aren't in Vanilla. Close again if wrong.

**Comment by anthonydillon** [comment]
I know I had seen it https://github.com/ubuntudesign/vanilla-framework/pull/377. 

Let's find out how this was dropped from master. I imagine it was merged into master while working on a future feature branch for v1. If that is the case, then we didn't merge the feature branch but force pushed it. We need to check what else was lost.

**Comment by yaili** [comment]
@anthonydillon Who should I assign to?

**Comment by anthonydillon** [comment]
I'm happy to do it. Merry Christmas!
