### ISSUE TITLE
Audit base typography

### ISSUE THREAD

**Issue by barrymcgee** [ubuntudesign/vanilla-framework#391]
## Context

- How many different weights of font should be included?
- This source currently has a lot of duplication, could this be reduced?
- Could base Ubuntu font be delivered in a more efficient manner?
- This file should only include styling directly on elements, typography helpers belong in overrides
- Type size across breakpoints should be reviewed - smaller or bigger on smaller screens?
- Vertical rhythm?

- Font variants should be:
 - normal 300
 - italic 300
 - normal 400
 - italic 400
 - mono 400

Font sizing should increase upwards in line with framework wide breakpoints.

Body copy:

14px > 15px > 16px

@yaili to confirm scaling up of headings & create separate issue to investigate vertical rhythm at a later date.

## Audit Checklist

- [ ] Browser testing
- [ ] Accessibility testing
- [ ] Sass linting
- [ ] Update documentation
- [ ] Convert sizing units to rems
- [ ]  Ensure only elements are styled directly

**Comment by yaili** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;3Pu8sZss&#x2F;1504-confirm-heading-sizes-across-3-breakpoints"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Confirm heading sizes across 3 breakpoints</a>
