### ISSUE TITLE
Audit buttons patterns

### ISSUE THREAD

**Issue by barrymcgee** [ubuntudesign/vanilla-framework#397]
## Context

Sanity check source code.

## Audit checklist

- [x] Browser testing
- [x] Accessibility testing
- [x] Sass linting
- [x] Update documentation
- [x] Convert sizing units to rems

**Comment by yaili** [comment]
The agreed buttons should follow Juju's:

- base (there is potential to possibly rename this, as it clashes with the name of the "Base/Basic" section of the pattern library)
- neutral
- positive
- negative
- brand (not in Juju, but gives the option of a brand coloured button, eg. orange in Ubuntu or aubergine in Canonical)
- --disabled (for all of the above)

**Comment by barrymcgee** [comment]
👌🏻

**Comment by barrymcgee** [comment]
@yaili Do we have designs for these for reference?

**Comment by yaili** [comment]
I've added them here, but the base button exported in a funny way: https://github.com/ubuntudesign/vanilla-design/tree/master/Buttons

**Comment by yaili** [comment]
Better now.

**Comment by spencerbygraves** [comment]
Just adding this as it shows the padding we have been using.

![buttons](https://cloud.githubusercontent.com/assets/9105999/17734375/cb46e1e2-6473-11e6-824e-d041896e9c6c.png)

**Comment by anthonydillon** [comment]
Also, here is my implementation of it including a few extra cloud one.
https://github.com/ubuntudesign/cloud-vanilla-theme/blob/master/scss/modules/_buttons.scss
