### ISSUE TITLE
[Proposal] Card pattern

### ISSUE THREAD

**Issue by barrymcgee** [ubuntudesign/vanilla-framework#411]
## Is this a proposal or an amendment?
 
__Proposal__

## Visual

<img width="582" alt="screenshot 2016-07-25 12 22 48" src="https://cloud.githubusercontent.com/assets/505570/17100471/7c5aee9e-5266-11e6-9a51-c03abb3aa938.png">

## Context

This pattern should be used by displaying a list of similar options in a grid or row. |t should also include a significant CTA.

## State

Possibly have rollover states? Drop shadows?

## Progressive enhancement

This pattern will probably need to take up all screen width on smaller screens, only showing one card in a vertical list on the smallest of screens. More cards can then be displayed in a horizontal row as screen real estate allows it.

**Comment by spencerbygraves** [comment]
As discussed in today's working group meeting, below is an image of how we currently use cards and the styles. The Snappy example above has been updated by Karl.

![cards](https://cloud.githubusercontent.com/assets/9105999/17106691/370fa15e-5284-11e6-9e5f-65271f36554d.png)

**Comment by anthonydillon** [comment]
I do not think we need to include the styling of the content and layout
inside the box/card.

That can be handled with the grid and some bespoke styling.

**Comment by barrymcgee** [comment]
@anthonydillon I think you're right here Ant - it would seem that Card is more of a layout tool as a container than a defined pattern for it's contents.

**Comment by barrymcgee** [comment]
Cards and boxes have now been conflated with "Card" winning out.

**Comment by anthonydillon** [comment]
If we are removing box. What would the component naming for the default and
3 types be?

**Comment by spencerbygraves** [comment]
After talking with @yaili yesterday, we decided to include only the first two examples above in vanilla. Card with shadow and card with border.

**Comment by barrymcgee** [comment]
@anthonydillon Just for reference - any issue with [Proposal] is a talking point only, the issue to complete this work with finalised specs is a separate issue, in this case, #432

**Comment by magdalena-mirowicz** [comment]
@yaili I don't know if it's helpful but Alex and Paty from Client team have done quite a bit of work on card component last year - maybe worth checking if it can be reused?

**Comment by anthonydillon** [comment]
@barrymcgee I understand, was just discussing the naming of the component and variants.

**Comment by barrymcgee** [comment]
Work issue: #432
