### ISSUE TITLE
Add a small breakpoint

### ISSUE THREAD

**Issue by barrymcgee** [ubuntudesign/vanilla-framework#415]
Currently our first breakpoint by default is at 768px.

As our grid is setup so that any element below this has 100% width, this means that many components look too large at resolutions between ~400px and 768px. Adding a `$breakpoint-small` would give us more granular control over components.

Actions:

- Consult our stats to find out our most popular device resolutions at present.
- Cross references with our patterns to determine where the best place would be to place a "small" breakpoint

**Comment by yaili** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;wmwptJyT&#x2F;1492-define-small-breakpoint"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Define small breakpoint</a>

**Comment by barrymcgee** [comment]
When completing the settings audit (#443), I found that there was a setting called `$navigation-threshold` that was in effect acting as a 'small' breakpoint at 620px.

Therefore, I renamed it `$breakpoint-small`, setting the value as `620px` by default and moved it to the correct file accordingly.

This can be easily tweaked in future if we feel `620px` is the not the optimal small breakpoint but for now this issue has been addressed.

**Comment by yaili** [comment]
So only the navigation is using it? What about fonts?

**Comment by barrymcgee** [comment]
At present - breadcrumbs, header and search use it. However, these will all be refactored in turn.

If by fonts, you mean page headings, they do not currently use a small breakpoint but they will when they are refactored too.

**Comment by yaili** [comment]
OK. Was this breakpoint determined based on the navigation of ubuntu.com?

**Comment by barrymcgee** [comment]
@yaili That is my understanding, yes.

**Comment by yaili** [comment]
OK, that sounds random for Vanilla. I'm guessing we still need to determine something more appropriate.

**Comment by barrymcgee** [comment]
Sure, we can revise again. Once we have worked through a greater number of components and tested them in-browser, I reckon a more obvious breakpoint will reveal itself.
