### ISSUE TITLE
[Proposal] A border function

### ISSUE THREAD

**Issue by barrymcgee** [ubuntudesign/vanilla-framework#416]
# Proposal

## Is this a proposal or an amendment?

- Proposal

## Context

Currently - `.row` includes inherent styling that gives it a bottom border. the class `.no-border` has to be added to every row to remove this. As a result, any codebase using VF tends to have more instances of `.no-border` than it does rows with borders. 

This is also true for patterns such as "vertical dividers" which mix structure with styling to add a border-right.

## Proposal

Create a `border()` mixin which can be called on any element to add a border to it. It could take an optional argument of top/right/bottom/left to add a corresponding border only to that side.

**Comment by pmahnke** [comment]
Agreed:

1. remove borders from rows
2. don't need to create a border mixin
3. remove class .no-border
4. look at strip for border
