### ISSUE TITLE
Audit links

### ISSUE THREAD

**Issue by barrymcgee** [ubuntudesign/vanilla-framework#417]
The two use cases identified for VF have are:

* `.external`
* `.link-top`

These should be documented with examples.

## Audit checklist

- [x] Bemify Sass 
- [x] Convert sizing units to rems
- [x] Sass linting
- [x] Browser testing
- [x] Accessibility testing
- [x] Update documentation

**Comment by barrymcgee** [comment]
@yaili I think base link styles should include an underline for accessibility. 

@anthonydillon Did you implement underlines with a break for descenders? 

Ref: https://www.sitepoint.com/15-rules-making-accessible-links/

**Comment by yaili** [comment]
Base link styles should be regular font weight (400) with 1px cool grey bottom border.
