### ISSUE TITLE
Audit Header Pattern

### ISSUE THREAD

**Issue by barrymcgee** [ubuntudesign/vanilla-framework#420]
The current navigation is way too complex and should be rewritten from scratch:

* Remove second level nav
* Remove search box
* Primary use case is VF logo and 5 links
* These should list on small screens, not a grid and display inline on medium breakpoint

## Audit checklist

- [x] Bemify Sass 
- [x] Convert sizing units to rems
- [x] Namespace pattern with `p-`
- [x] Sass linting
- [x] Browser testing
- [x] Accessibility testing
- [x] Update documentation

**Comment by anthonydillon** [comment]
I find that our primary use case would include a search box. I think there
header is to complex to be a single component. It should be an organism of
a collection of components.

**Comment by barrymcgee** [comment]
@anthonydillon The criticism levelled at the current navigation most often is that it is too complex and too opinionated. 

When @yaili and I discussed this in our rationalisation workshop, we both agreed that the primary navigation for Vanilla should be as simple as it could possibly be - any further augmentation of additional complex functionality should happen a theme level.

**Comment by anthonydillon** [comment]
Thanks for explaining. Makes sense.
