### ISSUE TITLE
[Proposal] Add notifications/alerts

### ISSUE THREAD

**Issue by barrymcgee** [ubuntudesign/vanilla-framework#422]
# Pattern proposal/amendment

## Is this a proposal or an amendment?

- Proposal

## Context

VF should provide some way of providing user feedback - positive, negative and warning.

**Comment by anthonydillon** [comment]
Cloud notifications: https://github.com/CanonicalLtd/juju-design/tree/master/Notifications

**Comment by yaili** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;mKW9AeNR&#x2F;1548-define-notifications-alerts"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Define notifications&#x2F;alerts</a>

**Comment by barrymcgee** [comment]
Work issue: #458
