### ISSUE TITLE
Audit utility - .align-center

### ISSUE THREAD

**Issue by barrymcgee** [ubuntudesign/vanilla-framework#425]
The rule for `.align-center` is actually a text-align rule so should be deprecated in favour of `.u-text-center`

**Comment by anthonydillon** [comment]
The reason we changed it is because it actually centres all child display
elements such as text and images.

**Comment by barrymcgee** [comment]
@anthonydillon `text-align: center` will only center inline elements meaning it's currently possible to apply `.align-center` on a container of lists, figures, blockquotes etc and see nothing change. 

By explicitly calling this utility `.u-text-center`, there should be no ambiguity around expected results.

**Comment by anthonydillon** [comment]
`text-align: center` does in fact effect all the above. For example http://codepen.io/anthonydillon/pen/bZjwJk.

**Comment by barrymcgee** [comment]
@anthonydillon Err.. no, you're centering the text within block level elements, as expected with a util called `.u-text-center` on the parent. 

The elements themselves are not centering as a block element is inherently `width: 100%` so they're filling the full width of their parent.

If you constrain the width on any of them (which in the wild they could be inheriting) they will sit snug left.

http://codepen.io/anon/pen/vKaXqj
