### ISSUE TITLE
Audit utility .video-container

### ISSUE THREAD

**Issue by barrymcgee** [ubuntudesign/vanilla-framework#428]
This should be deprecated as responsive media is a tool defined further up the cascade.

**Comment by anthonydillon** [comment]
This utility is used by many sites. Do we really want to deprecate it?

**Comment by barrymcgee** [comment]
@anthonydillon Admittedly it's not ideal to deprecate classes that are widely used but we have a unique opportunity in `v1` (as it will be widely signposted as a big breaking change) to clean up aspects of the framework that will probably be considered too painful later on.

We are not removing the ability of Vanilla to cater for this use case of responsive video, just making the util that does it more broad in scope so it can also be used for use cases such as maps, social media embeds etc.

Even if we were to keep it as it, it would have to renamed to match our new namespace convention so change here is unavoidable either way.

**Comment by anthonydillon** [comment]
I understand. I thought the plan was to remove this functionally. If it's
just a rename or new implementation then I'm happy.
