### ISSUE TITLE
Remove sass linting dependency on ruby

### ISSUE THREAD

**Issue by nottrobin** [ubuntudesign/vanilla-framework#453]
As mentioned with regard to [cloud-vanilla-theme](https://github.com/ubuntudesign/cloud-vanilla-theme/issues/40), can `gulp-scss-lint` be replaced with a purely node-based solution?

**Comment by barrymcgee** [comment]
Robin has investigated `sass-lint ` which is a npm module. He will continue this work and test a solution in the offsite-sprint.
