### ISSUE TITLE
Add notifications/alerts

### ISSUE THREAD

**Issue by barrymcgee** [ubuntudesign/vanilla-framework#458]
This was a Proposal that was validated in the working group - see #422 

There is currently an on-going task to define how these alerts/notifications should look, see: https://trello.com/c/mKW9AeNR/1548-define-notifications-alerts

When further details are added to this issue, this work is be prioritised accordingly.

**Comment by yaili** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;mKW9AeNR&#x2F;1548-define-notifications-alerts"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Define notifications&#x2F;alerts</a>

**Comment by yaili** [comment]
Did we say this was for after v1?

**Comment by barrymcgee** [comment]
@yaili Ideally, for `v1`.

**Comment by yaili** [comment]
@faooful is working on it.

**Comment by barrymcgee** [comment]
@faooful If possible, can you add the alert/notifications designs to this spec before next Tuesday (when we kick off our off-site Vanilla sprint)?

**Comment by yaili** [comment]
@barrymcgee is this ok? https://github.com/ubuntudesign/vanilla-design/tree/master/Notifications
