### ISSUE TITLE
All modifiers should be extended using single class modification convention

### ISSUE THREAD

**Issue by anthonydillon** [ubuntudesign/vanilla-framework#463]
We should convert any instances where two classes are required to modify a pattern, such as:

### Multi classes modification
```html
<a href="" class="button">...</a>
<a href="" class="button button--positive">...</a>
```

..to a single class modification convention, such as:

### Single classes modification
```html
<a href="" class="button">...</a>
<a href="" class="button--positive">...</a>
```

**Comment by barrymcgee** [comment]
We've had a vote and decided as a team, we'll move forward with the single class modification convention.
