### ISSUE TITLE
Switch from NPM2 to NPM3

### ISSUE THREAD

**Issue by barrymcgee** [ubuntudesign/vanilla-framework#470]
We should upgrade to NPM 3. The improvements and key differences over NPM2 are documented here:

https://docs.npmjs.com/how-npm-works/npm3

- [ ] Test toolchain via NPM3 end to end
- [ ] Update documentation to reflect new toolchain and steps needed to install Vanilla via NPM

**Comment by nottrobin** [comment]
The NPM module nesting change does not effect `vanilla-framework` itself, as it has no sass dependencies, and no-where in this project either specifies an NPM version or is dependent on any specific version.

## Changes to themes

The place where NPM3 support needs to be implemented is in each Vanilla theme. Lines like [this one](https://github.com/ubuntudesign/canonical-vanilla-theme/blob/d51f9c9299e07428d6587046110304f5788c3034/scss/_theme.scss#L6) 

``` sass
@import '../node_modules/vanilla-framework/scss/vanilla';
```

Needs to be changed to:

``` sass
@import 'vanilla-framework/scss/vanilla';
```

E.g.: [in ubuntu-vanilla-theme](https://github.com/ubuntudesign/ubuntu-vanilla-theme/blob/master/scss/_theme.scss#L7).

The `node_modules` folder then needs to be included in the sass include path when the sass is built in any project which uses the theme.

It is perfectly safe to update this in each vanilla theme as soon as anyone gets to it. This will not break any sites as all the vanilla themes are versioned. However, when the new version for a theme is published, no site will be able to use the new version until it updates its build system to use NPM3 and set up the sass include path correctly.

## Actions

- Update themes to use the `@import 'vanilla-framework/scss/vanilla';` form as and when we get to theme
- When someone needs to update a site to use a more modern theme, ask @nottrobin to fix it for you, or ask him to explain how to do it yourself.
- The ubuntu-vanilla-theme has been updated to the more modern structure already, and so www.ubuntu.com will need fixing sooner than any other site, as soon as it needs the new theme version.

**Comment by nottrobin** [comment]
I've updated all the themes we currently have with issues to update to the new way of including vanilla:

- ubuntu-vanilla-theme [is already updated](https://github.com/ubuntudesign/ubuntu-vanilla-theme/blob/master/scss/_theme.scss#L7)
- [issue 31 in canonical-vanilla-theme](https://github.com/ubuntudesign/canonical-vanilla-theme/issues/31)
- [issue 43 in cloud-vanilla-theme](https://github.com/ubuntudesign/cloud-vanilla-theme/issues/43)
- [issue 10 in docs-vanilla-theme](https://github.com/ubuntudesign/docs-vanilla-theme/issues/10)
- [issue 4 in maas-gui-vanilla-theme](https://github.com/ubuntudesign/maas-gui-vanilla-theme/issues/4)
- [issue 1 in boilerplate-vanilla-theme](https://github.com/ubuntudesign/boilerplate-vanilla-theme/issues/1)
- [issue 2 in wordpress-vanilla-theme](https://github.com/ubuntudesign/wordpress-vanilla-theme/issues/2)
