### ISSUE TITLE
Code blocks should be on light grey, not black (design needed)

### ISSUE THREAD

**Issue by nottrobin** [ubuntudesign/vanilla-framework#487]
[Code blocks](http://vf.demo.haus/base/code/) are currently white text on black background. And this style is also used on [jujucharms.com/docs](https://jujucharms.com/docs/stable/getting-started):

![on black](http://i.imgur.com/bW76Ntk.png)

However, this is not used across the board, and I believe that his looks ugly and out-dated, and may have become the standard in vanilla sort of by accident. I much prefer the lighter style that is currently used on [snapcraft.io/docs](http://snapcraft.io/docs/core/install) and [maas.io/docs](http://maas.io/docs/installconfig-package-install):

![on light grey](http://i.imgur.com/T9DNimx.png)

Have at it!

**Comment by barrymcgee** [comment]
@magdalena-mirowicz should talk to Monica about User Testing

**Comment by barrymcgee** [comment]
The docs guys (who are in the office and participated in Vanilla standup this morning) have raised concerns about this change as they feel the light background looks too much like other page elements within docs?

@yaili Can you confirm the changes that should be made here?

**Comment by yaili** [comment]
Yes, changes applies to docs too.

**Comment by nottrobin** [comment]
Is the issue with the concept of light backgrounds in general, or specifically with the current code block styling as it [exists currently on docs.ubuntu.com](https://docs.ubuntu.com/core/en/guides/intro/security)?

The reason I suggested light code blocks is because this is the pattern used by [READMEs on GitHub](https://github.com/ubuntudesign/vanilla-framework/blob/master/README.md), [StackOverflow](http://stackoverflow.com/questions/41966055/parsing-xml-with-special-chars-using-elementtree), [Mozilla Developer Network](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Grammar_and_types#Basics), [The W3C](https://www.w3.org/wiki/HTML/Elements/body#Examples), [Wikipedia](https://en.wikipedia.org/wiki/Factory_method_pattern#Example_implementations), [DigitalOcean](https://www.digitalocean.com/community/tutorials/how-to-install-linux-apache-mysql-php-lamp-stack-on-ubuntu) [help.ubuntu.com](https://help.ubuntu.com/community/IptablesHowTo) and practically every other code block I've seen on the internet in the last 5 years.

Of course it's totally fine to iterate on the current design to ensure the code stands out to an appropriate degree.

**Comment by barrymcgee** [comment]
I've asked Peter to bring this issue to the attention of the docs guys so they can offer their opinion more clearly. They have a session with @yaili tomorrow and should discuss it then. Moving to Blocked until we have the outcome of that discussion.

**Comment by barrymcgee** [comment]
@yaili What was the outcome of this meeting?

**Comment by yaili** [comment]
- The design spec for code blocks will be updated to have darker border so there is more contrast with surrounding context
- We will implement syntax highlighting - should we do this in Vanilla straight away? I think it's worth doing it directly, I will add a proposal that we can add comments on
