### ISSUE TITLE
blockquote needs design review

### ISSUE THREAD

**Issue by pmahnke** [ubuntudesign/vanilla-framework#488]
# 1. Bug template

## Process

1. navigate to /base/blockquote/
2. see how small the cite text looks
3. see how large the blockquote text is
4. see how little space there is to the next paragraph
5. see how the last quote mark is absolutely positioned when you resize the browser, shouldn't it be next to the final text?

## Expected result

* larger citation text
* more space between quote and next paragraph
* right quote near the end text

## Screenshot

![image](https://cloud.githubusercontent.com/assets/441217/18086170/748bfc24-6ea6-11e6-81df-b1549ee31384.png)

**Comment by yaili** [comment]
Here is the large screen design: https://github.com/ubuntudesign/vanilla-design/tree/master/Pull%20quote

The text size should be the same as an h3, and the quotation marks size should be the same as an h1.

The bottom of the opening mark should align top to the text, and the top of the closing mark should align with bottom of text (see image).

Space between text and marks is 12px.

The design doesn't include the cite, but it should be a heading 4 size italic, 12px top margin.
