### ISSUE TITLE
Update negative colour

### ISSUE THREAD

**Issue by anthonydillon** [ubuntudesign/vanilla-framework#489]
## Is this a proposal or an amendment?
- Amendment

Its a change to the `$color-negative` variable

## Visual
Old accessibility: https://snook.ca/technical/colour_contrast/colour.html#fg=FFFFFF,bg=DF382C
New accessibility: https://snook.ca/technical/colour_contrast/colour.html#fg=FFFFFF,bg=DC382C

## Context
To make the negative notification meet AA accessibly I have updated the colour from `#DF382C` and `#DC382C`.

**Comment by barrymcgee** [comment]
@yaili to present this at the visual design catch-up.

**Comment by yaili** [comment]
This was accepted. I will create a separate issue to update the colour.

**Comment by yaili** [comment]
Related to #557
