### ISSUE TITLE
Update header/navigation pattern

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/vanilla-framework#517]
Please update pattern to match designs: https://github.com/ubuntudesign/vanilla-design/tree/master/Nav

Moved from https://github.com/ubuntudesign/vanillaframework.io/issues/21

**Comment by deadlight** [comment]
Related to: #573

**Comment by deadlight** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;7vtXM3Oj&#x2F;1742-fix-mobile-nav"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Fix mobile nav</a>
