### ISSUE TITLE
Include existing typographic scale

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/vanilla-framework#528]
# 1. Bug template

## Process

1. Go to base > typography in documentation

## Current result

The typographic scale seems to have been removed, the font sizes don't match the previously defined Vanilla styles.

## Expected result

It should be used the defined Vanilla style: http://design.ubuntu.com/web-style-guide/typography

We are in the process of updating the font sizes, but for now we should use the existing scale.

**Comment by pmahnke** [comment]
this is live now.
