### ISSUE TITLE
[various screen sizes] Checkboxes and radio buttons are vertically misaligned

### ISSUE THREAD

**Issue by magdalena-mirowicz** [ubuntudesign/vanilla-framework#550]
1. Use Samsung Galaxy III
2. Navigate to Forms pattern
3. Look at checkboxes and radio buttons - they seem vertically misaligned

**Comment by yaili** [comment]
Can you check again? There were some updates to forms yesterday. Thank you.

**Comment by magdalena-mirowicz** [comment]
It shows incorrectly on Samsung Galaxy III, iPhone 5s, Macbook Air

**Comment by yaili** [comment]
From Browserstack testing:
- Still a problem in Galaxy III with Android 4.1 - low priority
- Still a problem in iPhone 5S - medium priority

I'm guessing fixing in one will fix in all…
