### ISSUE TITLE
Update the colour palette to be WCAG compliant

### ISSUE THREAD

**Issue by richmccartney** [ubuntudesign/vanilla-framework#557]
## Is this a proposal or an amendment?

- Amendment

Colour pallet of the vanilla framework to be WCAG guideline compliant. 

## Context

The current pallet we have within vanilla doesn't comply and we should change all the colours to pass any tests. I suggest we could use a tool like http://colorsafe.co/ to select an acceptable pallet and then filter this through the framework and further to our themes.

**Comment by barrymcgee** [comment]
Design team are planning to do an accessibility audit of colors in the near future. In the meantime, we may need to tweak the Vanilla color palette for launch to meet accessibility criteria.

**Comment by yaili** [comment]
I have made a proposed accessible colour palette that needs to be approved: http://ubuntudesign.github.io/style-guides-content/vanilla/colours.html

**Comment by barrymcgee** [comment]
Fixed by #681
