### ISSUE TITLE
[Proposal] Grid-list and image-grid should be renamed

### ISSUE THREAD

**Issue by barrymcgee** [ubuntudesign/vanilla-framework#586]
# Pattern amendment

## Is this a proposal or an amendment?

- Amendment

`.p-grid-list` / `.p-image-grid`

## Context

in my opinion, the naming of these patterns is misleading as neither of them have anything to do with the actual grid which could easily lead to confusion given the underpin tenet of all CSS framework tends to be a grid.

## Proposed action

Rename both of these patterns so they don't reference 'grid'

**Comment by yaili** [comment]
We had agreed to call image-grid list-inline-images a few weeks ago. Don't know why this hasn't been changed yet.

**Comment by yaili** [comment]
I think the other one though, grid-list, is related to the grid.
