### ISSUE TITLE
Remove color-highlight variable

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/vanilla-framework#597]
There was bug filed last week to hide or remove the variable all together from Vanilla. Will this still be worked on?

**Comment by barrymcgee** [comment]
@yaili Are you sure that wasn't tabs? 

Either way - I can action this too as I agree it's a good call..

**Comment by yaili** [comment]
Don't think so… tabs had incorrect design (one of the incorrect things is that it was using orange).
