### ISSUE TITLE
[Proposal] Rename greys to be more abstract

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/vanilla-framework#606]
# 2. Pattern proposal/amendment

## Is this a proposal or an amendment?

- Amendment: Colours

## Context

At the moment we have the following grey colour variable names:

- light grey
- warm grey
- mid grey
- cool grey

Platform has:

- porcelain (light grey) #f7f7f7
- silk (warm grey) #cdcdcd
- graphite (mid grey) #666
- jet/inkstone (cool grey) - jet is #111111 and inkstone is #3b3b3b, there is no #333333 - I propose inkstone

The proposal is that Vanilla:

- rename the current greys to a naming system based on the strength of the grey with a number from (0-100), for example $color-grey-10, $color-grey-40, etc.
- maybe we can find an automated way to find out what is the closest percentage of the grey based on white/black spectrum
- any time we refer to the actual HEX values in the CSS, comment the real name of the colour, as we will use it internally

**Comment by yaili** [comment]
Updated proposed names:
- x-dark: black
- dark: #333333
- mid-dark: #666666
- mid-light: #cdcdcd
- light: #f7f7f7
- x-light: white

cc @spencerbygraves @anthonydillon @deadlight @kwm14 @barrymcgee @grahambancroft @faooful @richmccartney

**Comment by barrymcgee** [comment]
@yaili Are these new color changes signed off and confirmed? If so, they should make v1.

**Comment by yaili** [comment]
I think the naming of the greys in vanilla variables is up to us.
