### ISSUE TITLE
[Proposal] Change #888 to #666 to be more accessible

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/vanilla-framework#607]
# 2. Pattern proposal/amendment

## Is this a proposal or an amendment?

- Amendment: $color-mid-grey

We should be able to use mid grey (currently #888888) for less important bits of content (eg. a date stamp on a comment) but it's not compliant with Level AA of WCAG 2.0 at our base text size (16pt).

If we change it to #666666 it passes the contrast tests and is a colour that platform also uses.

**Comment by barrymcgee** [comment]
Fixed by #670
