### ISSUE TITLE
Add style for image-grid/list-inline-images back

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/vanilla-framework#615]
# 1. Bug template

## Process

1. Navigate to Patterns > Image grid

## Expected result

Expected to see the same pattern as in "A SELECTION OF OUR CLOUD PARTNERS" on this page http://www.ubuntu.com/cloud/partners

## Current result

Currently it shows an unstyled list.

**Comment by yaili** [comment]
The correct name for this pattern is list-inline-images, and not just inline-images as it's currently in the docs.

**Comment by barrymcgee** [comment]
@yaili By naming this a list, we are constraining its use semantically to lists only. Imo we should avoid naming our presentation classes with assumptions to underlying semantics.

By omitting list from the name, this pattern can be implemented either using a list;

```html
<ul class="p-inline-images">
    <li><img class="p-inline-images__img" src="http://placehold.it/150x200" alt="Placeholder image" /></li>
    </li><img class="p-inline-images__img" src="http://placehold.it/175x200" alt="Placeholder image" /></li>
    <li><img class="p-inline-images__img" src="http://placehold.it/150x200" alt="Placeholder image" /></li>
</ul>
```

...or simply a container holding a collection of images, which has certain accessibility advantages - namely that it can arduous for screen readers users listening to a screen reader call out list item 1 image, list item 2 image etc when it could just cycle quickly through the images one by one reading the alts .[1]

```html
<div class="p-inline-images">
    <img class="p-inline-images__img" src="http://placehold.it/150x200" alt="Placeholder image" />
    <img class="p-inline-images__img" src="http://placehold.it/175x200" alt="Placeholder image" />
    <img class="p-inline-images__img" src="http://placehold.it/150x200" alt="Placeholder image" />
</div>
```

[1] Related debate: https://css-tricks.com/navigation-in-lists-to-be-or-not-to-be/#reinhard
