### ISSUE TITLE
Code snippet not displaying correctly

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/vanilla-framework#621]
# 1. Bug template

## Process

1. Navigate to Patterns > Code snippet

## Expected result

Dark: https://github.com/ubuntudesign/vanilla-design/blob/master/Code/Code%20snippet%20dark.png

Light: https://github.com/ubuntudesign/vanilla-design/blob/master/Code/Code%20snippet%20light.png

## Current result

See screenshot below.

## Screenshot

<img width="894" alt="screen shot 2016-09-12 at 10 58 24" src="https://cloud.githubusercontent.com/assets/223966/18432055/edf51cfe-78d7-11e6-815e-13d7ba4f8249.png">

**Comment by yaili** [comment]
@barrymcgee Can this be done without JS?

**Comment by anthonydillon** [comment]
Copying to clipboard will require JavaScript.
