### ISSUE TITLE
[various screen sizes] /base/forms/ All form fields are too long

### ISSUE THREAD

**Issue by magdalena-mirowicz** [ubuntudesign/vanilla-framework#623]
## Process

1. Go to /base/forms/ on iPhone 5s
2. form fields don't fit the screen and look cut off on the right hand side

**Comment by magdalena-mirowicz** [comment]
They seem also too long on large screen so that's probably the reason for this issue

**Comment by joanasa89** [comment]
Go to base/forms/feedback classes
1. review the space between the fields, spacing equally  
2. align checkbox widgets with the description

please see the screenshot
![screen shot 2016-09-12 at 11 33 04](https://cloud.githubusercontent.com/assets/21334617/18432935/c2db880a-78dc-11e6-9881-9a3f14dd1b0a.png)

**Comment by barrymcgee** [comment]
Field width issue fixed by https://github.com/ubuntudesign/vanilla-framework/pull/609

**Comment by yaili** [comment]
Can't replicate on iPhone 5S. Checkboxes still misaligned but that's captured in #550
