### ISSUE TITLE
Quote in blockquote and typography is not displayed consistently

### ISSUE THREAD

**Issue by magdalena-mirowicz** [ubuntudesign/vanilla-framework#626]
## Process

1. Go to base/typography/ and /base/blockquote/
2. We have "Canonical" in one case and "-Canonical" in the other
3. I think it should be the same - @yaili please choose what you prefer

**Comment by yaili** [comment]
The example should say —Canonical, but any author can write what they want really. The blockquote page should be removed, there is a separate issue for that.
