### ISSUE TITLE
[ Samsung + nexus ]Menu navigation is not working

### ISSUE THREAD

**Issue by joanasa89** [ubuntudesign/vanilla-framework#629]
**Expected result**
Menu navigation should be working in the same way across different devices 

**Current result**
Currently, on samsung galaxy note II  (internet browser), samsung galaxy s II (internet browser & google chrome browser) + nexus 7 (google chrome browser) navigation **menu** is not working properly, only possible to access the options from "settings" accordion menu.

**Comment by barrymcgee** [comment]
I've tested and verified that this now works on Browserstack (Nexus 6, Google Chrome)
