### ISSUE TITLE
Google fonts won't work on cn.developer.ubuntu.com

### ISSUE THREAD

**Issue by anthonydillon** [ubuntudesign/vanilla-framework#63]
<beuno> mhall119, hi
 http://cn.developer.ubuntu.com/
 is using google fonts
 which, doesn't work in China

**Comment by anthonydillon** [comment]
just to update people...
we are working on it.
we have had to get IS to update assets.u.c mime-types and fix up the cross domain policy
https://rt.admin.canonical.com/Ticket/Display.html?id=78723&results=a26ccf06ff962431f614422179a19780
this is still in progress.
Peter

**Comment by richmccartney** [comment]
Adding this to the v0.0.13 milestone, could be achieved in the refactoring in our week sprint.

**Comment by anthonydillon** [comment]
Vanilla self hosts the Ubuntu font so this will work if using Vanilla.
