### ISSUE TITLE
/patterns/navigation - whole page needs rethinking

### ISSUE THREAD

**Issue by magdalena-mirowicz** [ubuntudesign/vanilla-framework#630]
## Process

[ordered list the process to finding and recreating the issue, example below]

1. Navigate to patterns > navigation
2. There is no description of the pattern and difference between 2 variants
3. Check pattern on small screen too

**Comment by yaili** [comment]
Related to #640

**Comment by barrymcgee** [comment]
This pattern has been refactored and tested and there is now only one variant in the docs to make it clearer.
