### ISSUE TITLE
[all screen sizes] /patterns/notifications - 1st example is overlapping the menu, other examples missing

### ISSUE THREAD

**Issue by magdalena-mirowicz** [ubuntudesign/vanilla-framework#632]
## Process

1. Go to: patterns/notification/
2. 1st notification example is overlapping menu or header
3. other examples are not showing at all

**Comment by yaili** [comment]
This is related to #667 and should be fixed when that's fixed.

**Comment by barrymcgee** [comment]
Fixed by #672
