### ISSUE TITLE
[various screen sizes] /patterns/pull-quote/ - problem with code block and quote patterns itself

### ISSUE THREAD

**Issue by magdalena-mirowicz** [ubuntudesign/vanilla-framework#634]
## Process

[ordered list the process to finding and recreating the issue, example below]

1. Navigate to Patterns > pull-quote
2. Text in code block is cut off
3. Quote doesn't look like it should - consult the designs

**Comment by yaili** [comment]
Design: https://github.com/ubuntudesign/vanilla-design/blob/master/Pull%20quote/Pull%20quote.png
