### ISSUE TITLE
[various screen sizes] /patterns/stepped-list/ - pattern issues

### ISSUE THREAD

**Issue by magdalena-mirowicz** [ubuntudesign/vanilla-framework#636]
## Process

1. Navigate to /patterns/stepped-list/
2. on large screen the number is squashed (screenshot attached below)
![screen shot 2016-09-12 at 14 31 24](https://cloud.githubusercontent.com/assets/16683435/18437738/28e5381c-78f6-11e6-95f2-dc96eefc8e2f.png)

3. on small screen the numbers are off completely (screenshot attached below)

![screen shot 2016-09-12 at 14 31 34](https://cloud.githubusercontent.com/assets/16683435/18437740/2b9b1c16-78f6-11e6-94cb-8e43f3355d5f.png)

**Comment by yaili** [comment]
This is not the correct style for stepped list, it seems to have regressed to previous versions.

Correct style: https://github.com/ubuntudesign/vanilla-design/blob/master/Lists/Stepped/Stepped.png
