### ISSUE TITLE
[Windows Edge 14, 13 & IE11] List with icons pattern issue

### ISSUE THREAD

**Issue by magdalena-mirowicz** [ubuntudesign/vanilla-framework#642]
## Process

[ordered list the process to finding and recreating the issue, example below]

1. Navigate to /patterns/lists/
2. Icons are not showing at all (see screensgrab) for lists with icons and lists with icons and dividers
![screen shot 2016-09-12 at 15 51 05](https://cloud.githubusercontent.com/assets/16683435/18440423/f9fef56e-7900-11e6-9416-618d0a6e5494.png)

**Comment by yaili** [comment]
@barrymcgee Something is happening that the SVG background images are not showing on latest version of Edge or IE 11 (it should render from 9 onwards). Can we please investigate this next week?
