### ISSUE TITLE
[Windows Edge 14, 13; IE 11] base/forms/ file input pattern is incorrect

### ISSUE THREAD

**Issue by magdalena-mirowicz** [ubuntudesign/vanilla-framework#643]
## Process

1. Navigate to base/forms/ 
2. Look at search pattern - it's not showing correctly

![screen shot 2016-09-12 at 16 06 55](https://cloud.githubusercontent.com/assets/16683435/18440977/096e4c82-7903-11e6-9116-c569cbc40979.png)

**Comment by yaili** [comment]
Tested on Browserstack. I don't think this is a bug, it's the IE/Edge default file input style.
