### ISSUE TITLE
Space between number and units

### ISSUE THREAD

**Issue by anthonydillon** [ubuntudesign/vanilla-framework#65]
In SASS, if you use an operation to calculate a value, you then have to concatenate the unit. If you just append the unit, the resulting compiled CSS has a space between number and unit.

Ex.
font-size: ($size / $base)em;
Compiles into:
font-size:2 em;

This is an error in CSS, because `2 em` is not an accepted property value. So, you need to concatenate the number and the unit, like this:

font-size:($size / $base)+em;
Compiles into:
font-size:2em;

DETAILS

Files:
core-mixins.scss lines 8-9-60-62-64
core.scss lines 212-218-222-228-283-286-457

UPDATE 2014-05-21

Concatenating number and unit turns the value into a string. In order to just convert a unit-less number to one with a unit, just multiply it for one desired unit.

E.g.
$size: 2;
$base: 1;
`($size / $base)em` compiles into `2 em` (not accepted property value)
`($size / $base) + em` compiles into `2em` (string - accepted by CSS, but may cause problems in SASS)
`($size / $base) * 1em` compiles into `2em` (number, em value - good both for CSS and SASS)

**Comment by anthonydillon** [comment]
From reporter: 

Actually the fix provided may cause error when the project grows. In fact, when you concatenate the number to its unit, the value is turned to a string, but you may still need to use it as a number (to make some operations, for example).

So, to avoid this problem, the right answer is:

font-size: (($size / $base) * 1px);

When the compiler makes the multiplication, the entire value is converted into pixels (and is still a number).

[Definitive patch for this issue.](https://bugs.launchpad.net/ubuntu-web-style-guide/+bug/1315882/+attachment/4116926/+files/units-patch.txt)

**Comment by yaili** [comment]
@anthonydillon What's the status on this?

**Comment by anthonydillon** [comment]
Still awaiting a fix.

**Comment by barrymcgee** [comment]
@anthonydillon Given that the files `core-mixins.scss` and `core.scss` no longer seem to exist in the repo and I can't find any examples of `$size / $base` either - is this bug obsolete?

**Comment by anthonydillon** [comment]
I believe so.
