### ISSUE TITLE
Probably unwanted behavior of the search box

### ISSUE THREAD

**Issue by anthonydillon** [ubuntudesign/vanilla-framework#66]
While using Web Style Guide for the Ubuntu-it website, I noticed that on Chromium a strange "x" appears on the search input when a value is provided.

After some investingations, I found that Chrome/Chromium and probably IE (I don't want to start it) appends a very ugly "x" in the right edge of all <input type="search" ...>, which is used to clear the input.
It doesn't happen on Firefox, or other browsers.

If you want to fix that, here is the css snippet for webkit:
input[type="search"]::-webkit-search-decoration,
input[type="search"]::-webkit-search-cancel-button,
input[type="search"]::-webkit-search-results-button,
input[type="search"]::-webkit-search-results-decoration { display: none; }

And this (untested) for IE:
input[type=text]::-ms-clear { display: none; width : 0; height: 0; }
input[type=text]::-ms-reveal { display: none; width : 0; height: 0; }

**Comment by richmccartney** [comment]
@anthonydillon Can you check if this is still effecting the search input styles. I believe my changes to the form.scss could have fixed it all now.

**Comment by anthonydillon** [comment]
I cant find a search on ubuntu-it site anymore. I imagine its fixed.

**Comment by yaili** [comment]
@anthonydillon Isn't this overriding default browser behaviour? How does this tie in with not styling select inputs?

**Comment by anthonydillon** [comment]
It is overriding the default behaviour but I think its a good thing to remove. We do style inputs but only slightly.

**Comment by yaili** [comment]
On a touchscreen having the option of erasing your previous search query with one tap is useful.

**Comment by anthonydillon** [comment]
Fair enough.
