### ISSUE TITLE
Built files contain errors

### ISSUE THREAD

**Issue by anthonydillon** [ubuntudesign/vanilla-framework#68]
eg: http://bazaar.launchpad.net/~canonical-webmonkeys/ubuntu-web-style-guide/trunk/view/head:/css/responsive/latest/core-grid-desktop.css which is now https://github.com/ubuntudesign/web-style-guide/blob/master/scss/_core-grid-desktop.scss

**Comment by yaili** [comment]
@anthonydillon Still a bug?

**Comment by anthonydillon** [comment]
No it has been removed.
