### ISSUE TITLE
Launch plan for v1.0

### ISSUE THREAD

**Issue by barrymcgee** [ubuntudesign/vanilla-framework#684]
- [x] Bump Vanilla version to 1.0.0-rc2
- [x] Update `docs-vanilla-theme` and test with new version
- [x] Bump vanillaframework.io to use latest docs-vanilla-theme and test
- [x] Remove `V1_RELEASE_NOTES.md` from repo
- [x] Check that gulp is optimising CSS build
- [x] Test all the things!
- [x] Write release notes
- [x] Bump to v1.0.0 if no show stopping bugs emerge
- [x] Update downstream deps
- [x] Configure DNS to docs.vanillaframework.io
- [x] Redirect `http://ubuntudesign.github.io/vanilla-framework/` to `http://docs.vanillaframework.io`

**Comment by barrymcgee** [comment]
@nottrobin I was looking into the current dynamic releases block on the `gh-pages` branch - where is the source for that index page?

**Comment by anthonydillon** [comment]
This is the script that builds the current project page:
https://github.com/ubuntudesign/vanilla-builder/blob/master/publish.sh
