### ISSUE TITLE
Uses relative urls for assets/images

### ISSUE THREAD

**Issue by anthonydillon** [ubuntudesign/vanilla-framework#69]
Relative urls for assets might be a problem if users are self hosting, so you'd either need to move those assets into this project or use absolute urls to a cdn?

**Comment by anthonydillon** [comment]
How are we going to do this? Should we work to make vanilla offline or submit to loading assets?

**Comment by yaili** [comment]
@anthonydillon Any conclusion on this?

**Comment by anthonydillon** [comment]
Vanilla need to remain offline so all assets used must be able to be overridden with a local path.
