### ISSUE TITLE
[Proposal] Admin name for MAAS and Landscape themes

### ISSUE THREAD

**Issue by anthonydillon** [ubuntudesign/vanilla-framework#691]
During our workshop. Me and Rich settled on the name "Admin" for CRUD like interfaces with dashboard. There were a number of other suggestions such as,
- config
- settings
- tool
- system
- service
- click and browse

All of which didn't fit the bill. What do you think?

**Comment by anthonydillon** [comment]
https://wrapbootstrap.com/theme/amaretti-responsive-admin-template-WB0696K5S

**Comment by yaili** [comment]
We will call it Dashboard.
