### ISSUE TITLE
Are we going to reformat theme names to vanilla-*-theme format?

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/vanilla-framework#697]
To be discussed in dev catch up, please.

**Comment by barrymcgee** [comment]
This was already discussed in a previous dev catch-up and agreed upon.

**Comment by yaili** [comment]
I thought so too, but others disagreed that it was agreed.

**Comment by barrymcgee** [comment]
🤔

**Comment by yaili** [comment]
@barrymcgee are we going to make this change? We're still saying "docs-vanilla-theme"

**Comment by barrymcgee** [comment]
`docs-vanilla-theme` has been renamed. All new themes will be named in the new format and issues have been added elsewhere to address cloud-vanilla-theme and maas-vanilla-theme
