### ISSUE TITLE
font-size in px's should be em

### ISSUE THREAD

**Issue by anthonydillon** [ubuntudesign/vanilla-framework#70]
Some elements have px font-size's applied. Forexample:

p, li, code, pre {
    font-size: 16px
    ...
}

These should use em's and only the body should have a px value.

**Comment by richmccartney** [comment]
@anthonydillon I think it would be cool if we used something like this http://www.sitepoint.com/sass-responsive-typography/ for fonts. Changing them to ```em``` or ```rem```'s totally agree.

**Comment by richmccartney** [comment]
Adding this to the v0.0.13 milestone, could be achieved in the refactoring in our week sprint.

**Comment by yaili** [comment]
Has this been done?

**Comment by anthonydillon** [comment]
No, font-sizes set to px's can be found in search and form components;
https://github.com/ubuntudesign/vanilla-framework/search?utf8=%E2%9C%93&q=font-size%3A

**Comment by anthonydillon** [comment]
This has cause issues adding vanilla to Juju GUI because it overrides the cascade.

**Comment by yaili** [comment]
@anthonydillon Is this still an issue?

**Comment by anthonydillon** [comment]
Only find them in forms but they are for mobile use so its ok.
