### ISSUE TITLE
.row should have adequate padding to use straight out of the box

### ISSUE THREAD

**Issue by barrymcgee** [ubuntudesign/vanilla-framework#701]
## Issue

Users should be able to pull down Vanilla and use it to build a basic page without writing any additional CSS. It would seem that the `.row` class in the grid setup does not have the correct padding to space elements in a consistent manner.
## Expected

You should be able to construct a simple page using rows, columns any basic elements without adding any additional CSS to rectify paddings/margins.

**Comment by yaili** [comment]
Do you mean top and bottom padding? Or something else?

**Comment by barrymcgee** [comment]
This has now been addressed by changes to `.p-strip`
