### ISSUE TITLE
Link to external source

### ISSUE THREAD

**Issue by bretonio** [ubuntudesign/vanilla-framework#704]
>On the project homepage, find the link to the latest build to add directly into your markup:

```
<link rel="stylesheet" href="https://assets.ubuntu.com/v1/vanilla-framework-version-x.x.x.min.css" />
```

I am not finding the link to the latest build at that URL.

**Comment by barrymcgee** [comment]
Hi @bretonio  - you need to replace `x.x.x` with the version number of Vanilla you wish to use. 

For example, if you want to pull in the latest release (`v1.0.1`), you would use;

`<link rel="stylesheet" href="https://assets.ubuntu.com/v1/vanilla-framework-version-1.0.1.min.css">`

**Comment by bretonio** [comment]
Thank you. A bonking the forehead moment! I just did not know where to look
for the version number.
