### ISSUE TITLE
Breadcrumb arrow does not align in Firefox

### ISSUE THREAD

**Issue by WillMoggridge** [ubuntudesign/vanilla-framework#707]
On Firefox, the greater than arrow does not align in Firefox. It appear correct in Chrome.
This at least applies to small screens, and may apply to larger viewports.

This was found on a small screen, while reviewing documentation builder for (docs.ubuntu.com) in https://github.com/nottrobin/documentation-builder/pull/3

## Screenshot

![selection_013](https://cloud.githubusercontent.com/assets/322693/19892018/a5579a5a-a03a-11e6-8b78-7b8ccec9c16e.png)

**Comment by barrymcgee** [comment]
@WillMoggridge Can you verify this bug still persists for you? I've carried out some testing and can't seem to replicate it. Here is Chrome and FF side-by-side:

<img width="852" alt="screenshot 2017-01-30 16 22 12" src="https://cloud.githubusercontent.com/assets/505570/22431208/a229b132-e708-11e6-8182-065d2352f510.png">

**Comment by WillMoggridge** [comment]
@barrymcgee  I can't seem to replicate this now. Looks like the problem may not exist anymore.
