### ISSUE TITLE
No variables to change url path to images

### ISSUE THREAD

**Issue by anthonydillon** [ubuntudesign/vanilla-framework#71]
MAAS needs to be able to work in an offline environment. This means that the paths embeded in the scss should easily be changed, using variables would make this a lot easier then having to find and replace all urls.

**Comment by yaili** [comment]
@anthonydillon @richmccartney Is this refactoring?

**Comment by anthonydillon** [comment]
I believe this is done now with the asset-server variable. We should try and keep Vanilla image free too if possible.
