### ISSUE TITLE
docs-vanilla-theme: Border on images

### ISSUE THREAD

**Issue by nottrobin** [ubuntudesign/vanilla-framework#718]
Filing this just to open a proposal discussion in the next vanilla workshop.

Should images in the official docs-vanilla-theme have a border?

For discussion see here: https://github.com/ubuntudesign/docs-vanilla-theme/issues/31

**Comment by yaili** [comment]
- @nottrobin will implement a new utility class in docs-vanilla-theme to add border
- Name of class: image-frame
- For now, there is not option to turn off image-frame in the markdown file, but we might add this option in the future
- There will be a class in content area that indicates the area uses image-frame

**Comment by yaili** [comment]
@nottrobin Can you make a copy of this in docs-vanilla and close here?
