### ISSUE TITLE
Remove IDs and replace with classes

### ISSUE THREAD

**Issue by anthonydillon** [ubuntudesign/vanilla-framework#72]
Deprecate all id selectors for classes. i.e,

```#main-content {
    ....
}```

to:

```#main-content,
.main-content {
    ....
}```

**Comment by nottrobin** [comment]
:heart: :+1:

**Comment by richmccartney** [comment]
Adding this to the v0.0.13 milestone, could be achieved in the refactoring in our week sprint.

**Comment by barrymcgee** [comment]
Searched the codebase and could no longer find any ID selections in the SCSS.
