### ISSUE TITLE
Site navigation should optionally display at $grid-max-width

### ISSUE THREAD

**Issue by anthonydillon** [ubuntudesign/vanilla-framework#721]
## Is this a proposal or an amendment?

- Amendment

If amendment, what is the name of the pattern to be amended?

## Visual

Currently:
![the leading operating system for pcs tablets phones iot devices servers and the cloud ubuntu](https://cloud.githubusercontent.com/assets/1413534/21307697/9a72b962-c5ce-11e6-8cb2-939fbe6a4878.png)

Desired:
![the leading operating system for pcs tablets phones iot devices servers and the cloud ubuntu](https://cloud.githubusercontent.com/assets/1413534/21307901/6c98c1f2-c5cf-11e6-8507-43ea06b4604c.png)

## Context

The navigation pattern is used by most sites. Some will like there navigation to be displayed full width like it is currently. Some sites will require the site navigation to be displayed at a limited width and centred.

**Comment by barrymcgee** [comment]
Was this discussed in WG?

**Comment by yaili** [comment]
I don't think so. It doesn't seem to have been labeled as proposal.

**Comment by anthonydillon** [comment]
We didn't, so let's talk about it in the sprint. It is one of the snags
from the Ubuntu on V1 prototype.

**Comment by anthonydillon** [comment]
There are two options here:
## Use a class name to switch the content from constrained to fluid
### Pros
 - This allows developers flexibility to change the width based on a markup class
### Cons
 - This allows developers to change nav width on different pages

## Create a setting `$nav-max-width` to constrain the nav but by default it's set to `$max-grid-width`
### Pros
 - One setting across the entire website
### Cons
- Developers need to mod a config file

## Going with none of the above
Option 3 use `.row` and fit the navigation to work with `.row`
