### ISSUE TITLE
The visibility patterns do not do all they promise

### ISSUE THREAD

**Issue by anthonydillon** [ubuntudesign/vanilla-framework#722]
## Is this a proposal or an amendment?

- Amendment

If amendment, what is the name of the pattern to be amended?
Visibility

## Context

The visibility patterns do not do everything they seem to promise. For example: `u-visible--small`. I would expect this to hide content on medium/large screens and only make the element visible on small screens.

**Comment by yaili** [comment]
To achieve this wouldn't you need to use: u-visible--small, u-hidden--medium, u-hidden--large?

**Comment by barrymcgee** [comment]
As @yaili says above - we deliberately decided that these utils should be explicit and not contain implicit rules.

**Comment by barrymcgee** [comment]
Superseded by #770
