### ISSUE TITLE
Grid only removes margin-left from the first col

### ISSUE THREAD

**Issue by anthonydillon** [ubuntudesign/vanilla-framework#725]
## Is this a proposal or an amendment?

- Amendment

Grid

## Context

Currently the grid system adds margin-left to all #-col items apart from the first item. This does not allow for more then one row of columns.

For example, many times to would do something like:

```html
<div class="8-col"> <!-- no margin-left -->
  <h2>Section heading</h2>
</div>
<div class="6-col"> <!-- has margin-left -->
  <p>some text</p>
</div>
<div class="6-col"> <!-- has margin-left -->
  <img src="..." />
</div>
```

The `6-cols` should align next to each other in this scenario.

**Comment by yaili** [comment]
What is the proposed change?

**Comment by anthonydillon** [comment]
Sorry should have been a bug not a proposal.

**Comment by barrymcgee** [comment]
Superseded by recent grid discussions
