### ISSUE TITLE
Design form validation

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/vanilla-framework#731]
We should agree on and design form validation for Vanilla. 

The existing [feedback classes](https://docs.vanillaframework.io/base/forms/) have a few problems:
- The outline colour overrides the focused colour
- There is no agreed place to display error messages
- Using only colour to convey error is not accessible - we could consider a combination of colour, icon, text
- Use aria (dev)

We should look at what is being used or what has been designed but not yet used in Juju and platform and see what makes sense to reuse. @kwm14 has also done work on this.

**Comment by kwm14** [comment]
These are the styles of feedback classes designed for MAAS, which have recently been implemented into first use journey.

**MAAS - Feedback classes**

![feedback-classes](https://cloud.githubusercontent.com/assets/17748020/21721224/4deb0e8c-d41f-11e6-87ef-6a7a625aaade.png)

**MAAS - First use journey**

![maas-fuj](https://cloud.githubusercontent.com/assets/17748020/21721226/51dc6356-d41f-11e6-9fb6-01eddd9e2c96.png)

**Comment by spencerbygraves** [comment]
I've attached 3 options below, none of which use float label as we do in Juju. I seem to remember we decided not to in Vanilla.

A - This is the same as Juju with the addition of icons as used in MAAS
B - As the yellow text isn't accessible on white (I tested #f99b11), I've moved the icons next to the message.
C - This removes the colour outline

I haven't used a green outline on any of them as I think that would be too much. And in most cases, do we even need to show success? In Juju we don't celebrate success in that way. An exception could be where the form is a checklist of items to be completed, as on Karl's example above.

B or C would be my choice, perhaps with the removal of green for success.

![image](https://cloud.githubusercontent.com/assets/9105999/21767293/25fad544-d66b-11e6-86e5-a9c08621215d.png)

**Comment by yaili** [comment]
Thanks, @spencerbygraves !

I prefer B. Some comments:
- Agree that red/yellow text in A isn't as legible as in B
- I think it's nice to see the whole input with the colour border
- I'm not sure about the icons inside the field, for example in checklists of radio buttons, it might be easier to keep consistency if the icon is outside, like in B
- We would need to be sure that the input maintains the outline glow when the keyboard is focused on it (as well as the colour) for accessibility

**Comment by spencerbygraves** [comment]
My comment above was wrong, we do show success on inputs in the inspector. We should keep the green success style and maybe outline the border as with the others.

You can see an example of the inspector here:

https://github.com/CanonicalLtd/juju-design/issues/176

**Comment by spencerbygraves** [comment]
![image](https://cloud.githubusercontent.com/assets/9105999/21848465/cb0ff936-d7f8-11e6-9dd6-81b9b5c73cc1.png)

**Comment by yaili** [comment]
Some fields will need help text. How does it look if a field with an error also has help text? Just stacks?

**Comment by spencerbygraves** [comment]
I can add that to the design. Although I guess the message can also be the help text, for example - "Your password should contain 8 characters or more."

**Comment by kwm14** [comment]
Thanks, @spencerbygraves 

I prefer design B too. Form validation is an ongoing problem is MAAS so your solution will help in resolving this, and it's a point we need to fix soon for accessibility.

As @yaili has pointed regarding help text, MAAS requires this for many input fields so would be great to see that visualised.

**Comment by spencerbygraves** [comment]
@kwm14 can you send me some examples of that help text please?

**Comment by kwm14** [comment]
@spencerbygraves this example is from the current Settings page, this is worse case scenario in MAAS so hopefully it helps.

### Settings - Network configuration 
![network-config-error](https://cloud.githubusercontent.com/assets/17748020/22016996/4c9443e4-dca0-11e6-8760-a46077e59b76.png)

**Comment by spencerbygraves** [comment]
Thanks @kwm14 Here's a version showing some of the text from MAAS:

![image](https://cloud.githubusercontent.com/assets/9105999/22018964/4dff8c9e-dca9-11e6-931c-556d4c442bbe.png)

**Comment by yaili** [comment]
I just noticed the text alignment of the labels above the fields. Could they be left aligned instead of having to have a left margin? I think it's easier to keep things correctly aligned in text that isn't inside a box doesn't have padding. Thoughts?

**Comment by kwm14** [comment]
@spencerbygraves looking good!

Agree with @yaili on making the label text and help text left aligned rather than matching the alignment of text inside the input field.

**Comment by spencerbygraves** [comment]
Sure, that's fine.

![image](https://cloud.githubusercontent.com/assets/9105999/22019385/55bb12c6-dcab-11e6-9155-2b4e17f2ef25.png)

**Comment by kwm14** [comment]
@spencerbygraves +1

**Comment by spencerbygraves** [comment]
Favoured option B, left aligned and with help text:

![image](https://cloud.githubusercontent.com/assets/9105999/22020022/f1df5dae-dcad-11e6-80c0-6a80556bd836.png)

**Comment by spencerbygraves** [comment]
Here are the agreed updates from yesterday:

![image](https://cloud.githubusercontent.com/assets/9105999/22286505/5f3e9696-e2e7-11e6-8f5e-aaac21530a17.png)

**Comment by yaili** [comment]
Some comments from the Vanilla sprint:

To be in line with the design of notifications, can we update this design to include the type of message, for example:

 **Error:** Label error text.

Is the colour of the help text #666666?

For the error messages to be consistent, it's probably best if it doesn't change colour. Thoughts?

The "error" icon is similar to the "clear" icon that is common inside search and other input fields. Have we considered that? Something to also think about in the notifications, as it uses the same icon.

**Comment by jamiedawsonyoung** [comment]
**Error message:**
I think the bolder weight for the message and the usual weight (light) for the label makes sense to me but I think we should look at an example of it before going ahead no? 

**Icons:**
The icon for errors is an issue we're already trying to tackle in the client team (or really with @tiheum). We had a session a few weeks ago (might be months now!) where Matthieu pulled together and highlighted the issues. However we then needed a follow up session on what to do about the problem… Which hasn't happened. [The deck he made for that session is here](https://docs.google.com/a/canonical.com/presentation/d/1BlgupBwIOVPnl7VGX-xiABi-0QtdFmCecFKYeiNMDnY/edit?usp=sharing). It would be good to finish that conversation and maybe even have a core set of icons that Vanilla can use?

**Comment by spencerbygraves** [comment]
As Jamie says, Matthieu is in the process of making those icons consistent. I've added the label, and I think keeping the text colour the same makes sense.

![image](https://cloud.githubusercontent.com/assets/9105999/22328279/50f186c6-e3b3-11e6-8b11-4f9f1b029b0d.png)
