### ISSUE TITLE
Why are we not using a list within the main nav pattern?

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/vanilla-framework#749]
# 1. Bug template

## Process

1. Navigate to https://docs.vanillaframework.io/patterns/navigation/
2. Look at the example markup used

## Expected result

That the nav element is marked up with a list, as the content in the example is a list of items.

According to the HTML5 spec:

> In cases where the content of a nav element represents a list of items, use list markup to aid understanding and navigation.

http://w3c.github.io/html/sections.html#the-nav-element

The only example in the spec that doesn't include a list shows navigation as part of a paragraph.

## Current result

It uses spans, divs and a elements.

**Comment by barrymcgee** [comment]
This was debated in the pre-v1 sprint in CitizenM. This article explains the reasoning: https://css-tricks.com/navigation-in-lists-to-be-or-not-to-be/

TL:DR The need for a nav to be a list pre-dates the <nav> HTML5 element and there's a strong argument from accessibility advocates that lists actually hinder a11y.

However, at the time @nottrobin felt strongly lists should be supported and did the work required so switching the markup to use lists is also supported.

**Comment by yaili** [comment]
I see. 

How do you convey hierarchy within the navigation items? Like:

- Cloud
  - OpenStack
- Desktop

If it's a list, why not mark it up as a list?

So in theory we could update the example in the docs?

**Comment by nottrobin** [comment]
I just read all the way through both posts, which I didn't have a chance to do during our Vanilla sprint last time.

I do like questioning our assumptions, and I like cleaner markup that uses fewer elements, but it should be noted that even Chris himself ultimately erred on the side of using lists in navigation:

> Personally, I think marking up navigation as lists seems to be the best choice. You can look at the facts and decide for yourself though.

[Wrapup of Navigation in Lists](https://css-tricks.com/wrapup-of-navigation-in-lists/)

Maybe it's worth revisiting this decision?

**Comment by yaili** [comment]
Agreed on working group to change the documentation to use lists.
