### ISSUE TITLE
Mention how to report bugs in both the README and the project homepage

### ISSUE THREAD

**Issue by nottrobin** [ubuntudesign/vanilla-framework#76]
Write something about reporting bugs (in Github issues) on the [README](README.md) and on the [project homepage](http://ubuntudesign.github.io/web-style-guide/).

**Comment by yaili** [comment]
Has this been done?

**Comment by anthonydillon** [comment]
Not yet. We need a small section in the README file with a link to the
issues and a brief description of what information is handy.
