### ISSUE TITLE
Automatically update latest release and description on project homepage

### ISSUE THREAD

**Issue by nottrobin** [ubuntudesign/vanilla-framework#78]
Because the [project homepage](ubuntudesign.github.io/web-style-guide/) is on Github Pages, everything is run through the Jekyll parser. This means we can add includes into the homepage. This could be leveraged to add dynamic content areas.

We should update the [jenkins build](http://jenkins.ubuntu.qa/job/release-web-style-guide/) to ask for a description for each new release, and then add the latest version number and the description to includes within the gh-pages branch, which can then be shown on the homepage.

I've created [a little example of what I mean](https://github.com/nottrobin/jekyll-sets/).

This would mean that to create a new release can be done entirely from Jenkins, and the publishing of the new version and the docs will happen automatically.

**Comment by barrymcgee** [comment]
@nottrobin This sounds like a really sweet idea - lack of documentation is a big gripe with Vanilla right now so anything we can do to improve that is a plus. Do you think you could get to this anytime soon?

**Comment by nottrobin** [comment]
I think this is already implemented isn't it? Unless you would like the existing implementation to be extended in some way?

**Comment by barrymcgee** [comment]
@nottrobin I read this as something else entirely.. sorry! But.. great work! :)
