### ISSUE TITLE
Prepare 1.1.4 release

### ISSUE THREAD

**Issue by barrymcgee** [ubuntudesign/vanilla-framework#790]
- Draft release notes
- Ensure all local tests pass

**Comment by barrymcgee** [comment]
**Remove collapsing margins on last-child elements**
We had previously included rules which attempted to be a catch-all to prevent double spacing inconsistencies. As with all attempted catch-alls, it proved to have unintended consequences. We’ve now removed it and will focus on removing any spacing irregularities at the component level.


**Add inherent bottom margin to .p-footer**
Footers will nearly always be the last element in a page, so we’ve added a bottom margin to stop this pattern from bumping into the bottom of the viewport.


**Ensure list tick icon stays grounded to top left of item**
This list icon had a habit of floating downward to track the lower portion of an expanding list item. It is now anchored. 


**Renaming `.u-text-align` to `.u-align`**
A wider use-case emerged where we needed to not only align text but also images. This util is now named more generically, and additional rules added so that it will align whatever a user places within it.


**Restrict .p-inline-images items width**
Images within this pattern will no longer be allowed to break the pattern even if their width exceeds the space allocated to each image within the pattern.


**Fix up breaking pattern - .p-matrix**
This pattern was updated to allow for multi-line content.


**Add .heading-* classes to mirror base heading styling**
Classes are now available so you could visually mirror heading styles 1-6 even if your element is semantically different.


**Fix equal height bugs**
This util was amended so that it did not alter the width of direct children, just the height.


**Update CONTRIBUTING.md**
The CONTRIBUTING.md has been reviewed and simplified.


**Updated link styles**
The default and pattern links have been updated to add colour and states.


**Added ignore rules to sass-listing**
The latest version `sass-lint` allows for block ignoring where violations are unavoidable. These rules are now present for a warning-free test report.


**Added spell check to the docs**
The `test` command now includes a spellcheck which will run over the docs to ensure all spellings are correct.


**Added bottom margin to grid columns**
Bottom margin equal to global gutter spacing is now part of the grid columns. This change will also be proposed upstream to Shelves grid.

**Comment by barrymcgee** [comment]
@yaili Release notes above - is there anything you think you'd need to QA?

**Comment by yaili** [comment]
Thanks. The inline images should align centre vertically, as I believe it did before. Doesn't seem to be doing that.
